// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="Bbox_RayIntersect,hls_ip_2019_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7vx485t-ffg1157-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=8.440000,HLS_SYN_LAT=14,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=30,HLS_SYN_FF=6035,HLS_SYN_LUT=5854,HLS_VERSION=2019_1}" *)

module Bbox_RayIntersect (
        ap_clk,
        ap_rst,
        ray_o_0,
        ray_o_1,
        ray_o_2,
        ray_d_0,
        ray_d_1,
        ray_d_2,
        ray_dRcp_0,
        ray_dRcp_1,
        ray_dRcp_2,
        ray_mint,
        ray_maxt,
        min_0,
        min_1,
        min_2,
        max_0,
        max_1,
        max_2,
        ap_return,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [31:0] ray_o_0;
input  [31:0] ray_o_1;
input  [31:0] ray_o_2;
input  [31:0] ray_d_0;
input  [31:0] ray_d_1;
input  [31:0] ray_d_2;
input  [31:0] ray_dRcp_0;
input  [31:0] ray_dRcp_1;
input  [31:0] ray_dRcp_2;
input  [31:0] ray_mint;
input  [31:0] ray_maxt;
input  [31:0] min_0;
input  [31:0] min_1;
input  [31:0] min_2;
input  [31:0] max_0;
input  [31:0] max_1;
input  [31:0] max_2;
output  [0:0] ap_return;
input   ap_ce;

reg   [31:0] ray_maxt_read_reg_2203;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_block_state14_pp0_stage0_iter13;
wire    ap_block_state15_pp0_stage0_iter14;
wire    ap_block_pp0_stage0_11001;
reg   [31:0] ray_maxt_read_reg_2203_pp0_iter1_reg;
reg   [31:0] ray_maxt_read_reg_2203_pp0_iter2_reg;
reg   [31:0] ray_maxt_read_reg_2203_pp0_iter3_reg;
reg   [31:0] ray_maxt_read_reg_2203_pp0_iter4_reg;
reg   [31:0] ray_maxt_read_reg_2203_pp0_iter5_reg;
reg   [31:0] ray_maxt_read_reg_2203_pp0_iter6_reg;
reg   [31:0] ray_maxt_read_reg_2203_pp0_iter7_reg;
reg   [31:0] ray_maxt_read_reg_2203_pp0_iter8_reg;
reg   [31:0] ray_maxt_read_reg_2203_pp0_iter9_reg;
reg   [31:0] ray_maxt_read_reg_2203_pp0_iter10_reg;
reg   [31:0] ray_maxt_read_reg_2203_pp0_iter11_reg;
reg   [31:0] ray_maxt_read_reg_2203_pp0_iter12_reg;
reg   [31:0] ray_mint_read_reg_2209;
reg   [31:0] ray_mint_read_reg_2209_pp0_iter1_reg;
reg   [31:0] ray_mint_read_reg_2209_pp0_iter2_reg;
reg   [31:0] ray_mint_read_reg_2209_pp0_iter3_reg;
reg   [31:0] ray_mint_read_reg_2209_pp0_iter4_reg;
reg   [31:0] ray_mint_read_reg_2209_pp0_iter5_reg;
reg   [31:0] ray_mint_read_reg_2209_pp0_iter6_reg;
reg   [31:0] ray_mint_read_reg_2209_pp0_iter7_reg;
reg   [31:0] ray_mint_read_reg_2209_pp0_iter8_reg;
reg   [31:0] ray_mint_read_reg_2209_pp0_iter9_reg;
reg   [31:0] ray_mint_read_reg_2209_pp0_iter10_reg;
reg   [31:0] ray_mint_read_reg_2209_pp0_iter11_reg;
reg   [31:0] ray_mint_read_reg_2209_pp0_iter12_reg;
reg   [31:0] ray_dRcp_2_read_reg_2215;
reg   [31:0] ray_dRcp_2_read_reg_2215_pp0_iter1_reg;
reg   [31:0] ray_dRcp_2_read_reg_2215_pp0_iter2_reg;
reg   [31:0] ray_dRcp_2_read_reg_2215_pp0_iter3_reg;
reg   [31:0] ray_dRcp_1_read_reg_2221;
reg   [31:0] ray_dRcp_1_read_reg_2221_pp0_iter1_reg;
reg   [31:0] ray_dRcp_1_read_reg_2221_pp0_iter2_reg;
reg   [31:0] ray_dRcp_1_read_reg_2221_pp0_iter3_reg;
reg   [31:0] ray_dRcp_0_read_reg_2227;
reg   [31:0] ray_dRcp_0_read_reg_2227_pp0_iter1_reg;
reg   [31:0] ray_dRcp_0_read_reg_2227_pp0_iter2_reg;
reg   [31:0] ray_dRcp_0_read_reg_2227_pp0_iter3_reg;
wire   [0:0] icmp_ln42_fu_364_p2;
reg   [0:0] icmp_ln42_reg_2284;
wire   [0:0] icmp_ln42_1_fu_370_p2;
reg   [0:0] icmp_ln42_1_reg_2289;
wire   [0:0] icmp_ln43_fu_412_p2;
reg   [0:0] icmp_ln43_reg_2294;
wire   [0:0] icmp_ln43_1_fu_418_p2;
reg   [0:0] icmp_ln43_1_reg_2299;
wire   [0:0] or_ln43_4_fu_436_p2;
reg   [0:0] or_ln43_4_reg_2304;
wire   [0:0] icmp_ln43_4_fu_460_p2;
reg   [0:0] icmp_ln43_4_reg_2310;
wire   [0:0] icmp_ln43_5_fu_466_p2;
reg   [0:0] icmp_ln43_5_reg_2315;
wire   [0:0] icmp_ln42_2_fu_490_p2;
reg   [0:0] icmp_ln42_2_reg_2332;
wire   [0:0] icmp_ln42_3_fu_496_p2;
reg   [0:0] icmp_ln42_3_reg_2337;
wire   [0:0] icmp_ln43_6_fu_538_p2;
reg   [0:0] icmp_ln43_6_reg_2342;
wire   [0:0] icmp_ln43_7_fu_544_p2;
reg   [0:0] icmp_ln43_7_reg_2347;
wire   [0:0] or_ln43_7_fu_562_p2;
reg   [0:0] or_ln43_7_reg_2352;
wire   [0:0] icmp_ln43_10_fu_586_p2;
reg   [0:0] icmp_ln43_10_reg_2358;
wire   [0:0] icmp_ln43_11_fu_592_p2;
reg   [0:0] icmp_ln43_11_reg_2363;
wire   [0:0] icmp_ln42_4_fu_616_p2;
reg   [0:0] icmp_ln42_4_reg_2380;
wire   [0:0] icmp_ln42_5_fu_622_p2;
reg   [0:0] icmp_ln42_5_reg_2385;
wire   [0:0] icmp_ln43_12_fu_664_p2;
reg   [0:0] icmp_ln43_12_reg_2390;
wire   [0:0] icmp_ln43_13_fu_670_p2;
reg   [0:0] icmp_ln43_13_reg_2395;
wire   [0:0] or_ln43_10_fu_688_p2;
reg   [0:0] or_ln43_10_reg_2400;
wire   [0:0] icmp_ln43_16_fu_712_p2;
reg   [0:0] icmp_ln43_16_reg_2406;
wire   [0:0] icmp_ln43_17_fu_718_p2;
reg   [0:0] icmp_ln43_17_reg_2411;
wire   [0:0] and_ln42_fu_728_p2;
reg   [0:0] and_ln42_reg_2416;
reg   [0:0] and_ln42_reg_2416_pp0_iter2_reg;
reg   [0:0] and_ln42_reg_2416_pp0_iter3_reg;
reg   [0:0] and_ln42_reg_2416_pp0_iter4_reg;
reg   [0:0] and_ln42_reg_2416_pp0_iter5_reg;
reg   [0:0] and_ln42_reg_2416_pp0_iter6_reg;
reg   [0:0] and_ln42_reg_2416_pp0_iter7_reg;
reg   [0:0] and_ln42_reg_2416_pp0_iter8_reg;
reg   [0:0] and_ln42_reg_2416_pp0_iter9_reg;
reg   [0:0] and_ln42_reg_2416_pp0_iter10_reg;
reg   [0:0] and_ln42_reg_2416_pp0_iter11_reg;
reg   [0:0] and_ln42_reg_2416_pp0_iter12_reg;
reg   [0:0] and_ln42_reg_2416_pp0_iter13_reg;
wire   [0:0] or_ln43_fu_764_p2;
reg   [0:0] or_ln43_reg_2424;
reg   [0:0] or_ln43_reg_2424_pp0_iter2_reg;
reg   [0:0] or_ln43_reg_2424_pp0_iter3_reg;
reg   [0:0] or_ln43_reg_2424_pp0_iter4_reg;
reg   [0:0] or_ln43_reg_2424_pp0_iter5_reg;
reg   [0:0] or_ln43_reg_2424_pp0_iter6_reg;
reg   [0:0] or_ln43_reg_2424_pp0_iter7_reg;
reg   [0:0] or_ln43_reg_2424_pp0_iter8_reg;
reg   [0:0] or_ln43_reg_2424_pp0_iter9_reg;
reg   [0:0] or_ln43_reg_2424_pp0_iter10_reg;
reg   [0:0] or_ln43_reg_2424_pp0_iter11_reg;
reg   [0:0] or_ln43_reg_2424_pp0_iter12_reg;
reg   [0:0] or_ln43_reg_2424_pp0_iter13_reg;
wire   [0:0] and_ln42_1_fu_774_p2;
reg   [0:0] and_ln42_1_reg_2430;
reg   [0:0] and_ln42_1_reg_2430_pp0_iter2_reg;
reg   [0:0] and_ln42_1_reg_2430_pp0_iter3_reg;
reg   [0:0] and_ln42_1_reg_2430_pp0_iter4_reg;
reg   [0:0] and_ln42_1_reg_2430_pp0_iter5_reg;
reg   [0:0] and_ln42_1_reg_2430_pp0_iter6_reg;
reg   [0:0] and_ln42_1_reg_2430_pp0_iter7_reg;
reg   [0:0] and_ln42_1_reg_2430_pp0_iter8_reg;
reg   [0:0] and_ln42_1_reg_2430_pp0_iter9_reg;
reg   [0:0] and_ln42_1_reg_2430_pp0_iter10_reg;
reg   [0:0] and_ln42_1_reg_2430_pp0_iter11_reg;
reg   [0:0] and_ln42_1_reg_2430_pp0_iter12_reg;
reg   [0:0] and_ln42_1_reg_2430_pp0_iter13_reg;
wire   [0:0] or_ln43_1_fu_810_p2;
reg   [0:0] or_ln43_1_reg_2439;
reg   [0:0] or_ln43_1_reg_2439_pp0_iter2_reg;
reg   [0:0] or_ln43_1_reg_2439_pp0_iter3_reg;
reg   [0:0] or_ln43_1_reg_2439_pp0_iter4_reg;
reg   [0:0] or_ln43_1_reg_2439_pp0_iter5_reg;
reg   [0:0] or_ln43_1_reg_2439_pp0_iter6_reg;
reg   [0:0] or_ln43_1_reg_2439_pp0_iter7_reg;
reg   [0:0] or_ln43_1_reg_2439_pp0_iter8_reg;
reg   [0:0] or_ln43_1_reg_2439_pp0_iter9_reg;
reg   [0:0] or_ln43_1_reg_2439_pp0_iter10_reg;
reg   [0:0] or_ln43_1_reg_2439_pp0_iter11_reg;
reg   [0:0] or_ln43_1_reg_2439_pp0_iter12_reg;
reg   [0:0] or_ln43_1_reg_2439_pp0_iter13_reg;
wire   [0:0] and_ln42_2_fu_820_p2;
reg   [0:0] and_ln42_2_reg_2445;
reg   [0:0] and_ln42_2_reg_2445_pp0_iter2_reg;
reg   [0:0] and_ln42_2_reg_2445_pp0_iter3_reg;
reg   [0:0] and_ln42_2_reg_2445_pp0_iter4_reg;
reg   [0:0] and_ln42_2_reg_2445_pp0_iter5_reg;
reg   [0:0] and_ln42_2_reg_2445_pp0_iter6_reg;
reg   [0:0] and_ln42_2_reg_2445_pp0_iter7_reg;
reg   [0:0] and_ln42_2_reg_2445_pp0_iter8_reg;
reg   [0:0] and_ln42_2_reg_2445_pp0_iter9_reg;
reg   [0:0] and_ln42_2_reg_2445_pp0_iter10_reg;
reg   [0:0] and_ln42_2_reg_2445_pp0_iter11_reg;
reg   [0:0] and_ln42_2_reg_2445_pp0_iter12_reg;
reg   [0:0] and_ln42_2_reg_2445_pp0_iter13_reg;
wire   [0:0] or_ln43_2_fu_856_p2;
reg   [0:0] or_ln43_2_reg_2454;
reg   [0:0] or_ln43_2_reg_2454_pp0_iter2_reg;
reg   [0:0] or_ln43_2_reg_2454_pp0_iter3_reg;
reg   [0:0] or_ln43_2_reg_2454_pp0_iter4_reg;
reg   [0:0] or_ln43_2_reg_2454_pp0_iter5_reg;
reg   [0:0] or_ln43_2_reg_2454_pp0_iter6_reg;
reg   [0:0] or_ln43_2_reg_2454_pp0_iter7_reg;
reg   [0:0] or_ln43_2_reg_2454_pp0_iter8_reg;
reg   [0:0] or_ln43_2_reg_2454_pp0_iter9_reg;
reg   [0:0] or_ln43_2_reg_2454_pp0_iter10_reg;
reg   [0:0] or_ln43_2_reg_2454_pp0_iter11_reg;
reg   [0:0] or_ln43_2_reg_2454_pp0_iter12_reg;
reg   [0:0] or_ln43_2_reg_2454_pp0_iter13_reg;
wire   [31:0] grp_fu_184_p2;
reg   [31:0] tmp_5_reg_2460;
wire   [31:0] grp_fu_190_p2;
reg   [31:0] tmp_7_reg_2465;
wire   [31:0] grp_fu_196_p2;
reg   [31:0] tmp_5_1_reg_2470;
wire   [31:0] grp_fu_202_p2;
reg   [31:0] tmp_7_1_reg_2475;
wire   [31:0] grp_fu_208_p2;
reg   [31:0] tmp_5_2_reg_2480;
wire   [31:0] grp_fu_214_p2;
reg   [31:0] tmp_7_2_reg_2485;
wire   [31:0] grp_fu_220_p2;
reg   [31:0] p_tmp_reg_2490;
reg   [31:0] p_tmp_reg_2490_pp0_iter7_reg;
wire   [31:0] grp_fu_224_p2;
reg   [31:0] p_b_read_assign_reg_2498;
reg   [31:0] p_b_read_assign_reg_2498_pp0_iter7_reg;
wire   [31:0] grp_fu_228_p2;
reg   [31:0] p_tmp_1_reg_2506;
reg   [31:0] p_tmp_1_reg_2506_pp0_iter7_reg;
wire   [31:0] grp_fu_232_p2;
reg   [31:0] p_b_read_assign_1_reg_2514;
reg   [31:0] p_b_read_assign_1_reg_2514_pp0_iter7_reg;
wire   [31:0] grp_fu_236_p2;
reg   [31:0] p_tmp_2_reg_2522;
reg   [31:0] p_tmp_2_reg_2522_pp0_iter7_reg;
reg   [31:0] p_tmp_2_reg_2522_pp0_iter8_reg;
reg   [31:0] p_tmp_2_reg_2522_pp0_iter9_reg;
wire   [31:0] grp_fu_240_p2;
reg   [31:0] p_b_read_assign_2_reg_2530;
reg   [31:0] p_b_read_assign_2_reg_2530_pp0_iter7_reg;
reg   [31:0] p_b_read_assign_2_reg_2530_pp0_iter8_reg;
reg   [31:0] p_b_read_assign_2_reg_2530_pp0_iter9_reg;
wire   [31:0] select_ln49_fu_944_p3;
reg   [31:0] select_ln49_reg_2538;
wire   [31:0] select_ln49_1_fu_950_p3;
reg   [31:0] select_ln49_1_reg_2545;
wire   [31:0] select_ln49_2_fu_1038_p3;
reg   [31:0] select_ln49_2_reg_2552;
reg   [31:0] select_ln49_2_reg_2552_pp0_iter9_reg;
wire   [31:0] select_ln49_3_fu_1044_p3;
reg   [31:0] select_ln49_3_reg_2559;
reg   [31:0] select_ln49_3_reg_2559_pp0_iter9_reg;
wire   [0:0] icmp_ln55_fu_1084_p2;
reg   [0:0] icmp_ln55_reg_2566;
wire   [0:0] icmp_ln55_1_fu_1090_p2;
reg   [0:0] icmp_ln55_1_reg_2571;
wire   [0:0] icmp_ln55_2_fu_1096_p2;
reg   [0:0] icmp_ln55_2_reg_2576;
wire   [0:0] icmp_ln55_3_fu_1102_p2;
reg   [0:0] icmp_ln55_3_reg_2581;
wire   [0:0] and_ln43_4_fu_1113_p2;
reg   [0:0] and_ln43_4_reg_2586;
reg   [0:0] and_ln43_4_reg_2586_pp0_iter10_reg;
reg   [0:0] and_ln43_4_reg_2586_pp0_iter11_reg;
reg   [0:0] and_ln43_4_reg_2586_pp0_iter12_reg;
reg   [0:0] and_ln43_4_reg_2586_pp0_iter13_reg;
wire   [31:0] select_ln43_fu_1118_p3;
reg   [31:0] select_ln43_reg_2591;
reg   [31:0] select_ln43_reg_2591_pp0_iter10_reg;
wire   [31:0] select_ln43_1_fu_1126_p3;
reg   [31:0] select_ln43_1_reg_2599;
reg   [31:0] select_ln43_1_reg_2599_pp0_iter10_reg;
wire   [0:0] and_ln55_1_fu_1148_p2;
reg   [0:0] and_ln55_1_reg_2607;
reg   [0:0] and_ln55_1_reg_2607_pp0_iter11_reg;
reg   [0:0] and_ln55_1_reg_2607_pp0_iter12_reg;
reg   [0:0] and_ln55_1_reg_2607_pp0_iter13_reg;
wire   [31:0] select_ln52_fu_1236_p3;
reg   [31:0] select_ln52_reg_2613;
wire   [31:0] select_ln53_fu_1324_p3;
reg   [31:0] select_ln53_reg_2620;
wire   [31:0] select_ln49_4_fu_1412_p3;
reg   [31:0] select_ln49_4_reg_2627;
reg   [31:0] select_ln49_4_reg_2627_pp0_iter11_reg;
wire   [31:0] select_ln49_5_fu_1418_p3;
reg   [31:0] select_ln49_5_reg_2634;
reg   [31:0] select_ln49_5_reg_2634_pp0_iter11_reg;
wire   [0:0] icmp_ln55_4_fu_1458_p2;
reg   [0:0] icmp_ln55_4_reg_2641;
wire   [0:0] icmp_ln55_5_fu_1464_p2;
reg   [0:0] icmp_ln55_5_reg_2646;
wire   [0:0] icmp_ln55_6_fu_1470_p2;
reg   [0:0] icmp_ln55_6_reg_2651;
wire   [0:0] icmp_ln55_7_fu_1476_p2;
reg   [0:0] icmp_ln55_7_reg_2656;
wire   [0:0] xor_ln43_1_fu_1482_p2;
reg   [0:0] xor_ln43_1_reg_2661;
reg   [0:0] xor_ln43_1_reg_2661_pp0_iter12_reg;
reg   [0:0] xor_ln43_1_reg_2661_pp0_iter13_reg;
wire   [0:0] and_ln43_9_fu_1487_p2;
reg   [0:0] and_ln43_9_reg_2666;
reg   [0:0] and_ln43_9_reg_2666_pp0_iter12_reg;
reg   [0:0] and_ln43_9_reg_2666_pp0_iter13_reg;
wire   [31:0] select_ln43_2_fu_1492_p3;
reg   [31:0] select_ln43_2_reg_2671;
reg   [31:0] select_ln43_2_reg_2671_pp0_iter12_reg;
wire   [31:0] select_ln43_3_fu_1499_p3;
reg   [31:0] select_ln43_3_reg_2679;
reg   [31:0] select_ln43_3_reg_2679_pp0_iter12_reg;
wire   [0:0] and_ln55_3_fu_1520_p2;
reg   [0:0] and_ln55_3_reg_2687;
reg   [0:0] and_ln55_3_reg_2687_pp0_iter13_reg;
wire   [31:0] select_ln52_1_fu_1608_p3;
reg   [31:0] select_ln52_1_reg_2693;
wire   [31:0] select_ln53_1_fu_1696_p3;
reg   [31:0] select_ln53_1_reg_2700;
wire   [0:0] icmp_ln55_8_fu_1736_p2;
reg   [0:0] icmp_ln55_8_reg_2707;
wire   [0:0] icmp_ln55_9_fu_1742_p2;
reg   [0:0] icmp_ln55_9_reg_2712;
wire   [0:0] icmp_ln55_10_fu_1748_p2;
reg   [0:0] icmp_ln55_10_reg_2717;
wire   [0:0] icmp_ln55_11_fu_1754_p2;
reg   [0:0] icmp_ln55_11_reg_2722;
wire   [0:0] xor_ln43_2_fu_1760_p2;
reg   [0:0] xor_ln43_2_reg_2727;
wire   [0:0] and_ln43_14_fu_1765_p2;
reg   [0:0] and_ln43_14_reg_2732;
wire   [31:0] select_ln43_4_fu_1770_p3;
wire   [31:0] select_ln43_5_fu_1777_p3;
wire   [0:0] icmp_ln60_fu_1819_p2;
reg   [0:0] icmp_ln60_reg_2747;
wire   [0:0] icmp_ln60_1_fu_1825_p2;
reg   [0:0] icmp_ln60_1_reg_2752;
wire   [0:0] icmp_ln60_2_fu_1831_p2;
reg   [0:0] icmp_ln60_2_reg_2757;
wire   [0:0] icmp_ln60_3_fu_1837_p2;
reg   [0:0] icmp_ln60_3_reg_2762;
wire   [0:0] icmp_ln60_4_fu_1878_p2;
reg   [0:0] icmp_ln60_4_reg_2767;
wire   [0:0] icmp_ln60_5_fu_1884_p2;
reg   [0:0] icmp_ln60_5_reg_2772;
wire   [0:0] icmp_ln60_6_fu_1890_p2;
reg   [0:0] icmp_ln60_6_reg_2777;
wire   [0:0] icmp_ln60_7_fu_1896_p2;
reg   [0:0] icmp_ln60_7_reg_2782;
wire    ap_block_pp0_stage0;
wire   [31:0] grp_fu_310_p1;
wire   [31:0] grp_fu_314_p0;
wire   [31:0] grp_fu_326_p1;
wire   [31:0] grp_fu_330_p0;
wire   [31:0] bitcast_ln42_fu_346_p1;
wire   [7:0] tmp_fu_350_p4;
wire   [22:0] trunc_ln42_fu_360_p1;
wire   [31:0] bitcast_ln43_fu_376_p1;
wire   [31:0] bitcast_ln43_1_fu_394_p1;
wire   [7:0] tmp_2_fu_380_p4;
wire   [22:0] trunc_ln43_fu_390_p1;
wire   [7:0] tmp_3_fu_398_p4;
wire   [22:0] trunc_ln43_1_fu_408_p1;
wire   [0:0] icmp_ln43_3_fu_430_p2;
wire   [0:0] icmp_ln43_2_fu_424_p2;
wire   [31:0] bitcast_ln43_2_fu_442_p1;
wire   [7:0] tmp_6_fu_446_p4;
wire   [22:0] trunc_ln43_2_fu_456_p1;
wire   [31:0] bitcast_ln42_1_fu_472_p1;
wire   [7:0] tmp_14_fu_476_p4;
wire   [22:0] trunc_ln42_1_fu_486_p1;
wire   [31:0] bitcast_ln43_3_fu_502_p1;
wire   [31:0] bitcast_ln43_4_fu_520_p1;
wire   [7:0] tmp_16_fu_506_p4;
wire   [22:0] trunc_ln43_3_fu_516_p1;
wire   [7:0] tmp_17_fu_524_p4;
wire   [22:0] trunc_ln43_4_fu_534_p1;
wire   [0:0] icmp_ln43_9_fu_556_p2;
wire   [0:0] icmp_ln43_8_fu_550_p2;
wire   [31:0] bitcast_ln43_5_fu_568_p1;
wire   [7:0] tmp_19_fu_572_p4;
wire   [22:0] trunc_ln43_5_fu_582_p1;
wire   [31:0] bitcast_ln42_2_fu_598_p1;
wire   [7:0] tmp_33_fu_602_p4;
wire   [22:0] trunc_ln42_2_fu_612_p1;
wire   [31:0] bitcast_ln43_6_fu_628_p1;
wire   [31:0] bitcast_ln43_7_fu_646_p1;
wire   [7:0] tmp_35_fu_632_p4;
wire   [22:0] trunc_ln43_6_fu_642_p1;
wire   [7:0] tmp_36_fu_650_p4;
wire   [22:0] trunc_ln43_7_fu_660_p1;
wire   [0:0] icmp_ln43_15_fu_682_p2;
wire   [0:0] icmp_ln43_14_fu_676_p2;
wire   [31:0] bitcast_ln43_8_fu_694_p1;
wire   [7:0] tmp_38_fu_698_p4;
wire   [22:0] trunc_ln43_8_fu_708_p1;
wire   [0:0] or_ln42_fu_724_p2;
wire   [0:0] grp_fu_244_p2;
wire   [0:0] or_ln43_3_fu_734_p2;
wire   [0:0] and_ln43_fu_738_p2;
wire   [0:0] grp_fu_250_p2;
wire   [0:0] or_ln43_5_fu_749_p2;
wire   [0:0] and_ln43_2_fu_753_p2;
wire   [0:0] grp_fu_256_p2;
wire   [0:0] and_ln43_1_fu_743_p2;
wire   [0:0] and_ln43_3_fu_758_p2;
wire   [0:0] or_ln42_1_fu_770_p2;
wire   [0:0] grp_fu_262_p2;
wire   [0:0] or_ln43_6_fu_780_p2;
wire   [0:0] and_ln43_5_fu_784_p2;
wire   [0:0] grp_fu_268_p2;
wire   [0:0] or_ln43_8_fu_795_p2;
wire   [0:0] and_ln43_7_fu_799_p2;
wire   [0:0] grp_fu_274_p2;
wire   [0:0] and_ln43_6_fu_789_p2;
wire   [0:0] and_ln43_8_fu_804_p2;
wire   [0:0] or_ln42_2_fu_816_p2;
wire   [0:0] grp_fu_280_p2;
wire   [0:0] or_ln43_9_fu_826_p2;
wire   [0:0] and_ln43_10_fu_830_p2;
wire   [0:0] grp_fu_286_p2;
wire   [0:0] or_ln43_11_fu_841_p2;
wire   [0:0] and_ln43_12_fu_845_p2;
wire   [0:0] grp_fu_292_p2;
wire   [0:0] and_ln43_11_fu_835_p2;
wire   [0:0] and_ln43_13_fu_850_p2;
wire   [31:0] bitcast_ln49_fu_862_p1;
wire   [31:0] bitcast_ln49_1_fu_879_p1;
wire   [7:0] tmp_s_fu_865_p4;
wire   [22:0] trunc_ln49_fu_875_p1;
wire   [0:0] icmp_ln49_1_fu_902_p2;
wire   [0:0] icmp_ln49_fu_896_p2;
wire   [7:0] tmp_8_fu_882_p4;
wire   [22:0] trunc_ln49_1_fu_892_p1;
wire   [0:0] icmp_ln49_3_fu_920_p2;
wire   [0:0] icmp_ln49_2_fu_914_p2;
wire   [0:0] or_ln49_fu_908_p2;
wire   [0:0] or_ln49_1_fu_926_p2;
wire   [0:0] and_ln49_fu_932_p2;
wire   [0:0] grp_fu_298_p2;
wire   [0:0] and_ln49_1_fu_938_p2;
wire   [31:0] bitcast_ln49_2_fu_956_p1;
wire   [31:0] bitcast_ln49_3_fu_973_p1;
wire   [7:0] tmp_21_fu_959_p4;
wire   [22:0] trunc_ln49_2_fu_969_p1;
wire   [0:0] icmp_ln49_5_fu_996_p2;
wire   [0:0] icmp_ln49_4_fu_990_p2;
wire   [7:0] tmp_22_fu_976_p4;
wire   [22:0] trunc_ln49_3_fu_986_p1;
wire   [0:0] icmp_ln49_7_fu_1014_p2;
wire   [0:0] icmp_ln49_6_fu_1008_p2;
wire   [0:0] or_ln49_2_fu_1002_p2;
wire   [0:0] or_ln49_3_fu_1020_p2;
wire   [0:0] and_ln49_2_fu_1026_p2;
wire   [0:0] grp_fu_302_p2;
wire   [0:0] and_ln49_3_fu_1032_p2;
wire   [31:0] bitcast_ln55_fu_1050_p1;
wire   [31:0] bitcast_ln55_1_fu_1067_p1;
wire   [7:0] tmp_11_fu_1053_p4;
wire   [22:0] trunc_ln55_fu_1063_p1;
wire   [7:0] tmp_12_fu_1070_p4;
wire   [22:0] trunc_ln55_1_fu_1080_p1;
wire   [0:0] xor_ln43_fu_1108_p2;
wire   [0:0] or_ln55_fu_1134_p2;
wire   [0:0] or_ln55_1_fu_1138_p2;
wire   [0:0] and_ln55_fu_1142_p2;
wire   [0:0] grp_fu_306_p2;
wire   [31:0] bitcast_ln215_fu_1154_p1;
wire   [31:0] bitcast_ln215_1_fu_1171_p1;
wire   [7:0] tmp_24_fu_1157_p4;
wire   [22:0] trunc_ln215_fu_1167_p1;
wire   [0:0] icmp_ln215_1_fu_1194_p2;
wire   [0:0] icmp_ln215_fu_1188_p2;
wire   [7:0] tmp_25_fu_1174_p4;
wire   [22:0] trunc_ln215_1_fu_1184_p1;
wire   [0:0] icmp_ln215_3_fu_1212_p2;
wire   [0:0] icmp_ln215_2_fu_1206_p2;
wire   [0:0] or_ln215_fu_1200_p2;
wire   [0:0] or_ln215_1_fu_1218_p2;
wire   [0:0] and_ln215_fu_1224_p2;
wire   [0:0] grp_fu_310_p2;
wire   [0:0] and_ln215_1_fu_1230_p2;
wire   [31:0] bitcast_ln192_fu_1242_p1;
wire   [31:0] bitcast_ln192_1_fu_1259_p1;
wire   [7:0] tmp_27_fu_1245_p4;
wire   [22:0] trunc_ln192_fu_1255_p1;
wire   [0:0] icmp_ln192_1_fu_1282_p2;
wire   [0:0] icmp_ln192_fu_1276_p2;
wire   [7:0] tmp_28_fu_1262_p4;
wire   [22:0] trunc_ln192_1_fu_1272_p1;
wire   [0:0] icmp_ln192_3_fu_1300_p2;
wire   [0:0] icmp_ln192_2_fu_1294_p2;
wire   [0:0] or_ln192_fu_1288_p2;
wire   [0:0] or_ln192_1_fu_1306_p2;
wire   [0:0] and_ln192_fu_1312_p2;
wire   [0:0] grp_fu_314_p2;
wire   [0:0] and_ln192_1_fu_1318_p2;
wire   [31:0] bitcast_ln49_4_fu_1330_p1;
wire   [31:0] bitcast_ln49_5_fu_1347_p1;
wire   [7:0] tmp_40_fu_1333_p4;
wire   [22:0] trunc_ln49_4_fu_1343_p1;
wire   [0:0] icmp_ln49_9_fu_1370_p2;
wire   [0:0] icmp_ln49_8_fu_1364_p2;
wire   [7:0] tmp_41_fu_1350_p4;
wire   [22:0] trunc_ln49_5_fu_1360_p1;
wire   [0:0] icmp_ln49_11_fu_1388_p2;
wire   [0:0] icmp_ln49_10_fu_1382_p2;
wire   [0:0] or_ln49_4_fu_1376_p2;
wire   [0:0] or_ln49_5_fu_1394_p2;
wire   [0:0] and_ln49_4_fu_1400_p2;
wire   [0:0] grp_fu_318_p2;
wire   [0:0] and_ln49_5_fu_1406_p2;
wire   [31:0] bitcast_ln55_2_fu_1424_p1;
wire   [31:0] bitcast_ln55_3_fu_1441_p1;
wire   [7:0] tmp_30_fu_1427_p4;
wire   [22:0] trunc_ln55_2_fu_1437_p1;
wire   [7:0] tmp_31_fu_1444_p4;
wire   [22:0] trunc_ln55_3_fu_1454_p1;
wire   [0:0] or_ln55_2_fu_1506_p2;
wire   [0:0] or_ln55_3_fu_1510_p2;
wire   [0:0] and_ln55_2_fu_1514_p2;
wire   [0:0] grp_fu_322_p2;
wire   [31:0] bitcast_ln215_2_fu_1526_p1;
wire   [31:0] bitcast_ln215_3_fu_1543_p1;
wire   [7:0] tmp_43_fu_1529_p4;
wire   [22:0] trunc_ln215_2_fu_1539_p1;
wire   [0:0] icmp_ln215_5_fu_1566_p2;
wire   [0:0] icmp_ln215_4_fu_1560_p2;
wire   [7:0] tmp_44_fu_1546_p4;
wire   [22:0] trunc_ln215_3_fu_1556_p1;
wire   [0:0] icmp_ln215_7_fu_1584_p2;
wire   [0:0] icmp_ln215_6_fu_1578_p2;
wire   [0:0] or_ln215_2_fu_1572_p2;
wire   [0:0] or_ln215_3_fu_1590_p2;
wire   [0:0] and_ln215_2_fu_1596_p2;
wire   [0:0] grp_fu_326_p2;
wire   [0:0] and_ln215_3_fu_1602_p2;
wire   [31:0] bitcast_ln192_2_fu_1614_p1;
wire   [31:0] bitcast_ln192_3_fu_1631_p1;
wire   [7:0] tmp_46_fu_1617_p4;
wire   [22:0] trunc_ln192_2_fu_1627_p1;
wire   [0:0] icmp_ln192_5_fu_1654_p2;
wire   [0:0] icmp_ln192_4_fu_1648_p2;
wire   [7:0] tmp_47_fu_1634_p4;
wire   [22:0] trunc_ln192_3_fu_1644_p1;
wire   [0:0] icmp_ln192_7_fu_1672_p2;
wire   [0:0] icmp_ln192_6_fu_1666_p2;
wire   [0:0] or_ln192_2_fu_1660_p2;
wire   [0:0] or_ln192_3_fu_1678_p2;
wire   [0:0] and_ln192_2_fu_1684_p2;
wire   [0:0] grp_fu_330_p2;
wire   [0:0] and_ln192_3_fu_1690_p2;
wire   [31:0] bitcast_ln55_4_fu_1702_p1;
wire   [31:0] bitcast_ln55_5_fu_1719_p1;
wire   [7:0] tmp_49_fu_1705_p4;
wire   [22:0] trunc_ln55_4_fu_1715_p1;
wire   [7:0] tmp_50_fu_1722_p4;
wire   [22:0] trunc_ln55_5_fu_1732_p1;
wire   [31:0] bitcast_ln60_fu_1784_p1;
wire   [31:0] bitcast_ln60_1_fu_1802_p1;
wire   [7:0] tmp_52_fu_1788_p4;
wire   [22:0] trunc_ln60_fu_1798_p1;
wire   [7:0] tmp_53_fu_1805_p4;
wire   [22:0] trunc_ln60_1_fu_1815_p1;
wire   [31:0] bitcast_ln60_2_fu_1843_p1;
wire   [31:0] bitcast_ln60_3_fu_1861_p1;
wire   [7:0] tmp_55_fu_1847_p4;
wire   [22:0] trunc_ln60_2_fu_1857_p1;
wire   [7:0] tmp_56_fu_1864_p4;
wire   [22:0] trunc_ln60_3_fu_1874_p1;
wire   [0:0] or_ln55_4_fu_1912_p2;
wire   [0:0] or_ln55_5_fu_1916_p2;
wire   [0:0] and_ln55_4_fu_1920_p2;
wire   [0:0] grp_fu_334_p2;
wire   [0:0] and_ln55_5_fu_1926_p2;
wire   [0:0] or_ln60_fu_1938_p2;
wire   [0:0] or_ln60_1_fu_1942_p2;
wire   [0:0] and_ln60_fu_1946_p2;
wire   [0:0] grp_fu_338_p2;
wire   [0:0] and_ln60_1_fu_1952_p2;
wire   [0:0] or_ln60_2_fu_1964_p2;
wire   [0:0] or_ln60_3_fu_1968_p2;
wire   [0:0] and_ln60_2_fu_1972_p2;
wire   [0:0] grp_fu_342_p2;
wire   [0:0] xor_ln55_fu_1902_p2;
wire   [0:0] xor_ln42_fu_1988_p2;
wire   [0:0] xor_ln55_1_fu_1907_p2;
wire   [0:0] xor_ln42_1_fu_2003_p2;
wire   [0:0] xor_ln55_2_fu_1932_p2;
wire   [0:0] xor_ln42_2_fu_2018_p2;
wire   [0:0] and_ln55_6_fu_1993_p2;
wire   [0:0] and_ln43_16_fu_1999_p2;
wire   [0:0] or_ln55_6_fu_2029_p2;
wire   [0:0] and_ln43_15_fu_1984_p2;
wire   [0:0] and_ln43_17_fu_2014_p2;
wire   [0:0] and_ln55_8_fu_2023_p2;
wire   [0:0] or_ln55_8_fu_2041_p2;
wire   [0:0] and_ln55_7_fu_2008_p2;
wire   [0:0] or_ln55_9_fu_2047_p2;
wire   [0:0] or_ln55_7_fu_2035_p2;
wire   [0:0] and_ln55_11_fu_2075_p2;
wire   [0:0] and_ln43_18_fu_2080_p2;
wire   [0:0] or_ln55_12_fu_2090_p2;
wire   [0:0] or_ln55_11_fu_2070_p2;
wire   [0:0] or_ln55_13_fu_2095_p2;
wire   [0:0] xor_ln55_3_fu_2101_p2;
wire   [0:0] and_ln43_20_fu_2107_p2;
wire   [0:0] or_ln55_14_fu_2117_p2;
wire   [0:0] or_ln55_15_fu_2122_p2;
wire   [0:0] and_ln55_9_fu_2059_p2;
wire   [0:0] and_ln55_10_fu_2065_p2;
wire   [0:0] or_ln55_17_fu_2139_p2;
wire   [0:0] or_ln55_16_fu_2134_p2;
wire   [0:0] and_ln55_12_fu_2144_p2;
wire   [0:0] and_ln43_19_fu_2085_p2;
wire   [0:0] and_ln43_21_fu_2112_p2;
wire   [0:0] xor_ln55_4_fu_2128_p2;
wire   [0:0] or_ln55_18_fu_2161_p2;
wire   [0:0] and_ln55_14_fu_2155_p2;
wire   [0:0] or_ln55_19_fu_2167_p2;
wire   [0:0] and_ln55_13_fu_2149_p2;
wire   [0:0] or_ln55_20_fu_2173_p2;
wire   [0:0] xor_ln60_fu_1958_p2;
wire   [0:0] or_ln55_10_fu_2053_p2;
wire   [0:0] sel_tmp116_fu_2179_p2;
wire   [0:0] tmp140_demorgan_fu_2185_p2;
wire   [0:0] and_ln60_3_fu_1978_p2;
wire   [0:0] tmp140_fu_2191_p2;
reg    grp_fu_184_ce;
reg    grp_fu_190_ce;
reg    grp_fu_196_ce;
reg    grp_fu_202_ce;
reg    grp_fu_208_ce;
reg    grp_fu_214_ce;
reg    grp_fu_220_ce;
reg    grp_fu_224_ce;
reg    grp_fu_228_ce;
reg    grp_fu_232_ce;
reg    grp_fu_236_ce;
reg    grp_fu_240_ce;
reg    grp_fu_244_ce;
wire    ap_block_pp0_stage0_00001;
reg    grp_fu_250_ce;
reg    grp_fu_256_ce;
reg    grp_fu_262_ce;
reg    grp_fu_268_ce;
reg    grp_fu_274_ce;
reg    grp_fu_280_ce;
reg    grp_fu_286_ce;
reg    grp_fu_292_ce;
reg    grp_fu_298_ce;
reg    grp_fu_302_ce;
reg    grp_fu_306_ce;
reg    grp_fu_310_ce;
reg    grp_fu_314_ce;
reg    grp_fu_318_ce;
reg    grp_fu_322_ce;
reg    grp_fu_326_ce;
reg    grp_fu_330_ce;
reg    grp_fu_334_ce;
reg    grp_fu_338_ce;
reg    grp_fu_342_ce;

rayIntersect_fsub_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
rayIntersect_fsub_32ns_32ns_32_4_full_dsp_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(min_0),
    .din1(ray_o_0),
    .ce(grp_fu_184_ce),
    .dout(grp_fu_184_p2)
);

rayIntersect_fsub_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
rayIntersect_fsub_32ns_32ns_32_4_full_dsp_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(max_0),
    .din1(ray_o_0),
    .ce(grp_fu_190_ce),
    .dout(grp_fu_190_p2)
);

rayIntersect_fsub_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
rayIntersect_fsub_32ns_32ns_32_4_full_dsp_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(min_1),
    .din1(ray_o_1),
    .ce(grp_fu_196_ce),
    .dout(grp_fu_196_p2)
);

rayIntersect_fsub_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
rayIntersect_fsub_32ns_32ns_32_4_full_dsp_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(max_1),
    .din1(ray_o_1),
    .ce(grp_fu_202_ce),
    .dout(grp_fu_202_p2)
);

rayIntersect_fsub_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
rayIntersect_fsub_32ns_32ns_32_4_full_dsp_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(min_2),
    .din1(ray_o_2),
    .ce(grp_fu_208_ce),
    .dout(grp_fu_208_p2)
);

rayIntersect_fsub_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
rayIntersect_fsub_32ns_32ns_32_4_full_dsp_1_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(max_2),
    .din1(ray_o_2),
    .ce(grp_fu_214_ce),
    .dout(grp_fu_214_p2)
);

rayIntersect_fmul_32ns_32ns_32_3_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
rayIntersect_fmul_32ns_32ns_32_3_max_dsp_1_U7(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_5_reg_2460),
    .din1(ray_dRcp_0_read_reg_2227_pp0_iter3_reg),
    .ce(grp_fu_220_ce),
    .dout(grp_fu_220_p2)
);

rayIntersect_fmul_32ns_32ns_32_3_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
rayIntersect_fmul_32ns_32ns_32_3_max_dsp_1_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_7_reg_2465),
    .din1(ray_dRcp_0_read_reg_2227_pp0_iter3_reg),
    .ce(grp_fu_224_ce),
    .dout(grp_fu_224_p2)
);

rayIntersect_fmul_32ns_32ns_32_3_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
rayIntersect_fmul_32ns_32ns_32_3_max_dsp_1_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_5_1_reg_2470),
    .din1(ray_dRcp_1_read_reg_2221_pp0_iter3_reg),
    .ce(grp_fu_228_ce),
    .dout(grp_fu_228_p2)
);

rayIntersect_fmul_32ns_32ns_32_3_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
rayIntersect_fmul_32ns_32ns_32_3_max_dsp_1_U10(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_7_1_reg_2475),
    .din1(ray_dRcp_1_read_reg_2221_pp0_iter3_reg),
    .ce(grp_fu_232_ce),
    .dout(grp_fu_232_p2)
);

rayIntersect_fmul_32ns_32ns_32_3_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
rayIntersect_fmul_32ns_32ns_32_3_max_dsp_1_U11(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_5_2_reg_2480),
    .din1(ray_dRcp_2_read_reg_2215_pp0_iter3_reg),
    .ce(grp_fu_236_ce),
    .dout(grp_fu_236_p2)
);

rayIntersect_fmul_32ns_32ns_32_3_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
rayIntersect_fmul_32ns_32ns_32_3_max_dsp_1_U12(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_7_2_reg_2485),
    .din1(ray_dRcp_2_read_reg_2215_pp0_iter3_reg),
    .ce(grp_fu_240_ce),
    .dout(grp_fu_240_p2)
);

rayIntersect_fcmp_32ns_32ns_1_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
rayIntersect_fcmp_32ns_32ns_1_2_1_U13(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ray_d_0),
    .din1(32'd0),
    .ce(grp_fu_244_ce),
    .opcode(5'd1),
    .dout(grp_fu_244_p2)
);

rayIntersect_fcmp_32ns_32ns_1_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
rayIntersect_fcmp_32ns_32ns_1_2_1_U14(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(min_0),
    .din1(ray_o_0),
    .ce(grp_fu_250_ce),
    .opcode(5'd2),
    .dout(grp_fu_250_p2)
);

rayIntersect_fcmp_32ns_32ns_1_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
rayIntersect_fcmp_32ns_32ns_1_2_1_U15(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(max_0),
    .din1(ray_o_0),
    .ce(grp_fu_256_ce),
    .opcode(5'd4),
    .dout(grp_fu_256_p2)
);

rayIntersect_fcmp_32ns_32ns_1_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
rayIntersect_fcmp_32ns_32ns_1_2_1_U16(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ray_d_1),
    .din1(32'd0),
    .ce(grp_fu_262_ce),
    .opcode(5'd1),
    .dout(grp_fu_262_p2)
);

rayIntersect_fcmp_32ns_32ns_1_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
rayIntersect_fcmp_32ns_32ns_1_2_1_U17(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(min_1),
    .din1(ray_o_1),
    .ce(grp_fu_268_ce),
    .opcode(5'd2),
    .dout(grp_fu_268_p2)
);

rayIntersect_fcmp_32ns_32ns_1_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
rayIntersect_fcmp_32ns_32ns_1_2_1_U18(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(max_1),
    .din1(ray_o_1),
    .ce(grp_fu_274_ce),
    .opcode(5'd4),
    .dout(grp_fu_274_p2)
);

rayIntersect_fcmp_32ns_32ns_1_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
rayIntersect_fcmp_32ns_32ns_1_2_1_U19(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ray_d_2),
    .din1(32'd0),
    .ce(grp_fu_280_ce),
    .opcode(5'd1),
    .dout(grp_fu_280_p2)
);

rayIntersect_fcmp_32ns_32ns_1_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
rayIntersect_fcmp_32ns_32ns_1_2_1_U20(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(min_2),
    .din1(ray_o_2),
    .ce(grp_fu_286_ce),
    .opcode(5'd2),
    .dout(grp_fu_286_p2)
);

rayIntersect_fcmp_32ns_32ns_1_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
rayIntersect_fcmp_32ns_32ns_1_2_1_U21(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(max_2),
    .din1(ray_o_2),
    .ce(grp_fu_292_ce),
    .opcode(5'd4),
    .dout(grp_fu_292_p2)
);

rayIntersect_fcmp_32ns_32ns_1_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
rayIntersect_fcmp_32ns_32ns_1_2_1_U22(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_tmp_reg_2490),
    .din1(p_b_read_assign_reg_2498),
    .ce(grp_fu_298_ce),
    .opcode(5'd2),
    .dout(grp_fu_298_p2)
);

rayIntersect_fcmp_32ns_32ns_1_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
rayIntersect_fcmp_32ns_32ns_1_2_1_U23(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_tmp_1_reg_2506),
    .din1(p_b_read_assign_1_reg_2514),
    .ce(grp_fu_302_ce),
    .opcode(5'd2),
    .dout(grp_fu_302_p2)
);

rayIntersect_fcmp_32ns_32ns_1_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
rayIntersect_fcmp_32ns_32ns_1_2_1_U24(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(select_ln49_1_reg_2545),
    .din1(select_ln49_reg_2538),
    .ce(grp_fu_306_ce),
    .opcode(5'd5),
    .dout(grp_fu_306_p2)
);

rayIntersect_fcmp_32ns_32ns_1_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
rayIntersect_fcmp_32ns_32ns_1_2_1_U25(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(select_ln49_3_reg_2559),
    .din1(grp_fu_310_p1),
    .ce(grp_fu_310_ce),
    .opcode(5'd4),
    .dout(grp_fu_310_p2)
);

rayIntersect_fcmp_32ns_32ns_1_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
rayIntersect_fcmp_32ns_32ns_1_2_1_U26(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_314_p0),
    .din1(select_ln49_2_reg_2552),
    .ce(grp_fu_314_ce),
    .opcode(5'd4),
    .dout(grp_fu_314_p2)
);

rayIntersect_fcmp_32ns_32ns_1_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
rayIntersect_fcmp_32ns_32ns_1_2_1_U27(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_tmp_2_reg_2522_pp0_iter8_reg),
    .din1(p_b_read_assign_2_reg_2530_pp0_iter8_reg),
    .ce(grp_fu_318_ce),
    .opcode(5'd2),
    .dout(grp_fu_318_p2)
);

rayIntersect_fcmp_32ns_32ns_1_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
rayIntersect_fcmp_32ns_32ns_1_2_1_U28(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(select_ln52_reg_2613),
    .din1(select_ln53_reg_2620),
    .ce(grp_fu_322_ce),
    .opcode(5'd5),
    .dout(grp_fu_322_p2)
);

rayIntersect_fcmp_32ns_32ns_1_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
rayIntersect_fcmp_32ns_32ns_1_2_1_U29(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(select_ln49_5_reg_2634),
    .din1(grp_fu_326_p1),
    .ce(grp_fu_326_ce),
    .opcode(5'd4),
    .dout(grp_fu_326_p2)
);

rayIntersect_fcmp_32ns_32ns_1_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
rayIntersect_fcmp_32ns_32ns_1_2_1_U30(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_330_p0),
    .din1(select_ln49_4_reg_2627),
    .ce(grp_fu_330_ce),
    .opcode(5'd4),
    .dout(grp_fu_330_p2)
);

rayIntersect_fcmp_32ns_32ns_1_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
rayIntersect_fcmp_32ns_32ns_1_2_1_U31(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(select_ln52_1_reg_2693),
    .din1(select_ln53_1_reg_2700),
    .ce(grp_fu_334_ce),
    .opcode(5'd5),
    .dout(grp_fu_334_p2)
);

rayIntersect_fcmp_32ns_32ns_1_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
rayIntersect_fcmp_32ns_32ns_1_2_1_U32(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(select_ln43_5_fu_1777_p3),
    .din1(ray_mint_read_reg_2209_pp0_iter12_reg),
    .ce(grp_fu_338_ce),
    .opcode(5'd3),
    .dout(grp_fu_338_p2)
);

rayIntersect_fcmp_32ns_32ns_1_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
rayIntersect_fcmp_32ns_32ns_1_2_1_U33(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(select_ln43_4_fu_1770_p3),
    .din1(ray_maxt_read_reg_2203_pp0_iter12_reg),
    .ce(grp_fu_342_ce),
    .opcode(5'd5),
    .dout(grp_fu_342_p2)
);

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        and_ln42_1_reg_2430 <= and_ln42_1_fu_774_p2;
        and_ln42_1_reg_2430_pp0_iter10_reg <= and_ln42_1_reg_2430_pp0_iter9_reg;
        and_ln42_1_reg_2430_pp0_iter11_reg <= and_ln42_1_reg_2430_pp0_iter10_reg;
        and_ln42_1_reg_2430_pp0_iter12_reg <= and_ln42_1_reg_2430_pp0_iter11_reg;
        and_ln42_1_reg_2430_pp0_iter13_reg <= and_ln42_1_reg_2430_pp0_iter12_reg;
        and_ln42_1_reg_2430_pp0_iter2_reg <= and_ln42_1_reg_2430;
        and_ln42_1_reg_2430_pp0_iter3_reg <= and_ln42_1_reg_2430_pp0_iter2_reg;
        and_ln42_1_reg_2430_pp0_iter4_reg <= and_ln42_1_reg_2430_pp0_iter3_reg;
        and_ln42_1_reg_2430_pp0_iter5_reg <= and_ln42_1_reg_2430_pp0_iter4_reg;
        and_ln42_1_reg_2430_pp0_iter6_reg <= and_ln42_1_reg_2430_pp0_iter5_reg;
        and_ln42_1_reg_2430_pp0_iter7_reg <= and_ln42_1_reg_2430_pp0_iter6_reg;
        and_ln42_1_reg_2430_pp0_iter8_reg <= and_ln42_1_reg_2430_pp0_iter7_reg;
        and_ln42_1_reg_2430_pp0_iter9_reg <= and_ln42_1_reg_2430_pp0_iter8_reg;
        and_ln42_2_reg_2445 <= and_ln42_2_fu_820_p2;
        and_ln42_2_reg_2445_pp0_iter10_reg <= and_ln42_2_reg_2445_pp0_iter9_reg;
        and_ln42_2_reg_2445_pp0_iter11_reg <= and_ln42_2_reg_2445_pp0_iter10_reg;
        and_ln42_2_reg_2445_pp0_iter12_reg <= and_ln42_2_reg_2445_pp0_iter11_reg;
        and_ln42_2_reg_2445_pp0_iter13_reg <= and_ln42_2_reg_2445_pp0_iter12_reg;
        and_ln42_2_reg_2445_pp0_iter2_reg <= and_ln42_2_reg_2445;
        and_ln42_2_reg_2445_pp0_iter3_reg <= and_ln42_2_reg_2445_pp0_iter2_reg;
        and_ln42_2_reg_2445_pp0_iter4_reg <= and_ln42_2_reg_2445_pp0_iter3_reg;
        and_ln42_2_reg_2445_pp0_iter5_reg <= and_ln42_2_reg_2445_pp0_iter4_reg;
        and_ln42_2_reg_2445_pp0_iter6_reg <= and_ln42_2_reg_2445_pp0_iter5_reg;
        and_ln42_2_reg_2445_pp0_iter7_reg <= and_ln42_2_reg_2445_pp0_iter6_reg;
        and_ln42_2_reg_2445_pp0_iter8_reg <= and_ln42_2_reg_2445_pp0_iter7_reg;
        and_ln42_2_reg_2445_pp0_iter9_reg <= and_ln42_2_reg_2445_pp0_iter8_reg;
        and_ln42_reg_2416 <= and_ln42_fu_728_p2;
        and_ln42_reg_2416_pp0_iter10_reg <= and_ln42_reg_2416_pp0_iter9_reg;
        and_ln42_reg_2416_pp0_iter11_reg <= and_ln42_reg_2416_pp0_iter10_reg;
        and_ln42_reg_2416_pp0_iter12_reg <= and_ln42_reg_2416_pp0_iter11_reg;
        and_ln42_reg_2416_pp0_iter13_reg <= and_ln42_reg_2416_pp0_iter12_reg;
        and_ln42_reg_2416_pp0_iter2_reg <= and_ln42_reg_2416;
        and_ln42_reg_2416_pp0_iter3_reg <= and_ln42_reg_2416_pp0_iter2_reg;
        and_ln42_reg_2416_pp0_iter4_reg <= and_ln42_reg_2416_pp0_iter3_reg;
        and_ln42_reg_2416_pp0_iter5_reg <= and_ln42_reg_2416_pp0_iter4_reg;
        and_ln42_reg_2416_pp0_iter6_reg <= and_ln42_reg_2416_pp0_iter5_reg;
        and_ln42_reg_2416_pp0_iter7_reg <= and_ln42_reg_2416_pp0_iter6_reg;
        and_ln42_reg_2416_pp0_iter8_reg <= and_ln42_reg_2416_pp0_iter7_reg;
        and_ln42_reg_2416_pp0_iter9_reg <= and_ln42_reg_2416_pp0_iter8_reg;
        and_ln43_14_reg_2732 <= and_ln43_14_fu_1765_p2;
        and_ln43_4_reg_2586 <= and_ln43_4_fu_1113_p2;
        and_ln43_4_reg_2586_pp0_iter10_reg <= and_ln43_4_reg_2586;
        and_ln43_4_reg_2586_pp0_iter11_reg <= and_ln43_4_reg_2586_pp0_iter10_reg;
        and_ln43_4_reg_2586_pp0_iter12_reg <= and_ln43_4_reg_2586_pp0_iter11_reg;
        and_ln43_4_reg_2586_pp0_iter13_reg <= and_ln43_4_reg_2586_pp0_iter12_reg;
        and_ln43_9_reg_2666 <= and_ln43_9_fu_1487_p2;
        and_ln43_9_reg_2666_pp0_iter12_reg <= and_ln43_9_reg_2666;
        and_ln43_9_reg_2666_pp0_iter13_reg <= and_ln43_9_reg_2666_pp0_iter12_reg;
        and_ln55_1_reg_2607 <= and_ln55_1_fu_1148_p2;
        and_ln55_1_reg_2607_pp0_iter11_reg <= and_ln55_1_reg_2607;
        and_ln55_1_reg_2607_pp0_iter12_reg <= and_ln55_1_reg_2607_pp0_iter11_reg;
        and_ln55_1_reg_2607_pp0_iter13_reg <= and_ln55_1_reg_2607_pp0_iter12_reg;
        and_ln55_3_reg_2687 <= and_ln55_3_fu_1520_p2;
        and_ln55_3_reg_2687_pp0_iter13_reg <= and_ln55_3_reg_2687;
        icmp_ln42_1_reg_2289 <= icmp_ln42_1_fu_370_p2;
        icmp_ln42_2_reg_2332 <= icmp_ln42_2_fu_490_p2;
        icmp_ln42_3_reg_2337 <= icmp_ln42_3_fu_496_p2;
        icmp_ln42_4_reg_2380 <= icmp_ln42_4_fu_616_p2;
        icmp_ln42_5_reg_2385 <= icmp_ln42_5_fu_622_p2;
        icmp_ln42_reg_2284 <= icmp_ln42_fu_364_p2;
        icmp_ln43_10_reg_2358 <= icmp_ln43_10_fu_586_p2;
        icmp_ln43_11_reg_2363 <= icmp_ln43_11_fu_592_p2;
        icmp_ln43_12_reg_2390 <= icmp_ln43_12_fu_664_p2;
        icmp_ln43_13_reg_2395 <= icmp_ln43_13_fu_670_p2;
        icmp_ln43_16_reg_2406 <= icmp_ln43_16_fu_712_p2;
        icmp_ln43_17_reg_2411 <= icmp_ln43_17_fu_718_p2;
        icmp_ln43_1_reg_2299 <= icmp_ln43_1_fu_418_p2;
        icmp_ln43_4_reg_2310 <= icmp_ln43_4_fu_460_p2;
        icmp_ln43_5_reg_2315 <= icmp_ln43_5_fu_466_p2;
        icmp_ln43_6_reg_2342 <= icmp_ln43_6_fu_538_p2;
        icmp_ln43_7_reg_2347 <= icmp_ln43_7_fu_544_p2;
        icmp_ln43_reg_2294 <= icmp_ln43_fu_412_p2;
        icmp_ln55_10_reg_2717 <= icmp_ln55_10_fu_1748_p2;
        icmp_ln55_11_reg_2722 <= icmp_ln55_11_fu_1754_p2;
        icmp_ln55_1_reg_2571 <= icmp_ln55_1_fu_1090_p2;
        icmp_ln55_2_reg_2576 <= icmp_ln55_2_fu_1096_p2;
        icmp_ln55_3_reg_2581 <= icmp_ln55_3_fu_1102_p2;
        icmp_ln55_4_reg_2641 <= icmp_ln55_4_fu_1458_p2;
        icmp_ln55_5_reg_2646 <= icmp_ln55_5_fu_1464_p2;
        icmp_ln55_6_reg_2651 <= icmp_ln55_6_fu_1470_p2;
        icmp_ln55_7_reg_2656 <= icmp_ln55_7_fu_1476_p2;
        icmp_ln55_8_reg_2707 <= icmp_ln55_8_fu_1736_p2;
        icmp_ln55_9_reg_2712 <= icmp_ln55_9_fu_1742_p2;
        icmp_ln55_reg_2566 <= icmp_ln55_fu_1084_p2;
        icmp_ln60_1_reg_2752 <= icmp_ln60_1_fu_1825_p2;
        icmp_ln60_2_reg_2757 <= icmp_ln60_2_fu_1831_p2;
        icmp_ln60_3_reg_2762 <= icmp_ln60_3_fu_1837_p2;
        icmp_ln60_4_reg_2767 <= icmp_ln60_4_fu_1878_p2;
        icmp_ln60_5_reg_2772 <= icmp_ln60_5_fu_1884_p2;
        icmp_ln60_6_reg_2777 <= icmp_ln60_6_fu_1890_p2;
        icmp_ln60_7_reg_2782 <= icmp_ln60_7_fu_1896_p2;
        icmp_ln60_reg_2747 <= icmp_ln60_fu_1819_p2;
        or_ln43_10_reg_2400 <= or_ln43_10_fu_688_p2;
        or_ln43_1_reg_2439 <= or_ln43_1_fu_810_p2;
        or_ln43_1_reg_2439_pp0_iter10_reg <= or_ln43_1_reg_2439_pp0_iter9_reg;
        or_ln43_1_reg_2439_pp0_iter11_reg <= or_ln43_1_reg_2439_pp0_iter10_reg;
        or_ln43_1_reg_2439_pp0_iter12_reg <= or_ln43_1_reg_2439_pp0_iter11_reg;
        or_ln43_1_reg_2439_pp0_iter13_reg <= or_ln43_1_reg_2439_pp0_iter12_reg;
        or_ln43_1_reg_2439_pp0_iter2_reg <= or_ln43_1_reg_2439;
        or_ln43_1_reg_2439_pp0_iter3_reg <= or_ln43_1_reg_2439_pp0_iter2_reg;
        or_ln43_1_reg_2439_pp0_iter4_reg <= or_ln43_1_reg_2439_pp0_iter3_reg;
        or_ln43_1_reg_2439_pp0_iter5_reg <= or_ln43_1_reg_2439_pp0_iter4_reg;
        or_ln43_1_reg_2439_pp0_iter6_reg <= or_ln43_1_reg_2439_pp0_iter5_reg;
        or_ln43_1_reg_2439_pp0_iter7_reg <= or_ln43_1_reg_2439_pp0_iter6_reg;
        or_ln43_1_reg_2439_pp0_iter8_reg <= or_ln43_1_reg_2439_pp0_iter7_reg;
        or_ln43_1_reg_2439_pp0_iter9_reg <= or_ln43_1_reg_2439_pp0_iter8_reg;
        or_ln43_2_reg_2454 <= or_ln43_2_fu_856_p2;
        or_ln43_2_reg_2454_pp0_iter10_reg <= or_ln43_2_reg_2454_pp0_iter9_reg;
        or_ln43_2_reg_2454_pp0_iter11_reg <= or_ln43_2_reg_2454_pp0_iter10_reg;
        or_ln43_2_reg_2454_pp0_iter12_reg <= or_ln43_2_reg_2454_pp0_iter11_reg;
        or_ln43_2_reg_2454_pp0_iter13_reg <= or_ln43_2_reg_2454_pp0_iter12_reg;
        or_ln43_2_reg_2454_pp0_iter2_reg <= or_ln43_2_reg_2454;
        or_ln43_2_reg_2454_pp0_iter3_reg <= or_ln43_2_reg_2454_pp0_iter2_reg;
        or_ln43_2_reg_2454_pp0_iter4_reg <= or_ln43_2_reg_2454_pp0_iter3_reg;
        or_ln43_2_reg_2454_pp0_iter5_reg <= or_ln43_2_reg_2454_pp0_iter4_reg;
        or_ln43_2_reg_2454_pp0_iter6_reg <= or_ln43_2_reg_2454_pp0_iter5_reg;
        or_ln43_2_reg_2454_pp0_iter7_reg <= or_ln43_2_reg_2454_pp0_iter6_reg;
        or_ln43_2_reg_2454_pp0_iter8_reg <= or_ln43_2_reg_2454_pp0_iter7_reg;
        or_ln43_2_reg_2454_pp0_iter9_reg <= or_ln43_2_reg_2454_pp0_iter8_reg;
        or_ln43_4_reg_2304 <= or_ln43_4_fu_436_p2;
        or_ln43_7_reg_2352 <= or_ln43_7_fu_562_p2;
        or_ln43_reg_2424 <= or_ln43_fu_764_p2;
        or_ln43_reg_2424_pp0_iter10_reg <= or_ln43_reg_2424_pp0_iter9_reg;
        or_ln43_reg_2424_pp0_iter11_reg <= or_ln43_reg_2424_pp0_iter10_reg;
        or_ln43_reg_2424_pp0_iter12_reg <= or_ln43_reg_2424_pp0_iter11_reg;
        or_ln43_reg_2424_pp0_iter13_reg <= or_ln43_reg_2424_pp0_iter12_reg;
        or_ln43_reg_2424_pp0_iter2_reg <= or_ln43_reg_2424;
        or_ln43_reg_2424_pp0_iter3_reg <= or_ln43_reg_2424_pp0_iter2_reg;
        or_ln43_reg_2424_pp0_iter4_reg <= or_ln43_reg_2424_pp0_iter3_reg;
        or_ln43_reg_2424_pp0_iter5_reg <= or_ln43_reg_2424_pp0_iter4_reg;
        or_ln43_reg_2424_pp0_iter6_reg <= or_ln43_reg_2424_pp0_iter5_reg;
        or_ln43_reg_2424_pp0_iter7_reg <= or_ln43_reg_2424_pp0_iter6_reg;
        or_ln43_reg_2424_pp0_iter8_reg <= or_ln43_reg_2424_pp0_iter7_reg;
        or_ln43_reg_2424_pp0_iter9_reg <= or_ln43_reg_2424_pp0_iter8_reg;
        p_b_read_assign_1_reg_2514 <= grp_fu_232_p2;
        p_b_read_assign_1_reg_2514_pp0_iter7_reg <= p_b_read_assign_1_reg_2514;
        p_b_read_assign_2_reg_2530 <= grp_fu_240_p2;
        p_b_read_assign_2_reg_2530_pp0_iter7_reg <= p_b_read_assign_2_reg_2530;
        p_b_read_assign_2_reg_2530_pp0_iter8_reg <= p_b_read_assign_2_reg_2530_pp0_iter7_reg;
        p_b_read_assign_2_reg_2530_pp0_iter9_reg <= p_b_read_assign_2_reg_2530_pp0_iter8_reg;
        p_b_read_assign_reg_2498 <= grp_fu_224_p2;
        p_b_read_assign_reg_2498_pp0_iter7_reg <= p_b_read_assign_reg_2498;
        p_tmp_1_reg_2506 <= grp_fu_228_p2;
        p_tmp_1_reg_2506_pp0_iter7_reg <= p_tmp_1_reg_2506;
        p_tmp_2_reg_2522 <= grp_fu_236_p2;
        p_tmp_2_reg_2522_pp0_iter7_reg <= p_tmp_2_reg_2522;
        p_tmp_2_reg_2522_pp0_iter8_reg <= p_tmp_2_reg_2522_pp0_iter7_reg;
        p_tmp_2_reg_2522_pp0_iter9_reg <= p_tmp_2_reg_2522_pp0_iter8_reg;
        p_tmp_reg_2490 <= grp_fu_220_p2;
        p_tmp_reg_2490_pp0_iter7_reg <= p_tmp_reg_2490;
        ray_dRcp_0_read_reg_2227 <= ray_dRcp_0;
        ray_dRcp_0_read_reg_2227_pp0_iter1_reg <= ray_dRcp_0_read_reg_2227;
        ray_dRcp_0_read_reg_2227_pp0_iter2_reg <= ray_dRcp_0_read_reg_2227_pp0_iter1_reg;
        ray_dRcp_0_read_reg_2227_pp0_iter3_reg <= ray_dRcp_0_read_reg_2227_pp0_iter2_reg;
        ray_dRcp_1_read_reg_2221 <= ray_dRcp_1;
        ray_dRcp_1_read_reg_2221_pp0_iter1_reg <= ray_dRcp_1_read_reg_2221;
        ray_dRcp_1_read_reg_2221_pp0_iter2_reg <= ray_dRcp_1_read_reg_2221_pp0_iter1_reg;
        ray_dRcp_1_read_reg_2221_pp0_iter3_reg <= ray_dRcp_1_read_reg_2221_pp0_iter2_reg;
        ray_dRcp_2_read_reg_2215 <= ray_dRcp_2;
        ray_dRcp_2_read_reg_2215_pp0_iter1_reg <= ray_dRcp_2_read_reg_2215;
        ray_dRcp_2_read_reg_2215_pp0_iter2_reg <= ray_dRcp_2_read_reg_2215_pp0_iter1_reg;
        ray_dRcp_2_read_reg_2215_pp0_iter3_reg <= ray_dRcp_2_read_reg_2215_pp0_iter2_reg;
        ray_maxt_read_reg_2203 <= ray_maxt;
        ray_maxt_read_reg_2203_pp0_iter10_reg <= ray_maxt_read_reg_2203_pp0_iter9_reg;
        ray_maxt_read_reg_2203_pp0_iter11_reg <= ray_maxt_read_reg_2203_pp0_iter10_reg;
        ray_maxt_read_reg_2203_pp0_iter12_reg <= ray_maxt_read_reg_2203_pp0_iter11_reg;
        ray_maxt_read_reg_2203_pp0_iter1_reg <= ray_maxt_read_reg_2203;
        ray_maxt_read_reg_2203_pp0_iter2_reg <= ray_maxt_read_reg_2203_pp0_iter1_reg;
        ray_maxt_read_reg_2203_pp0_iter3_reg <= ray_maxt_read_reg_2203_pp0_iter2_reg;
        ray_maxt_read_reg_2203_pp0_iter4_reg <= ray_maxt_read_reg_2203_pp0_iter3_reg;
        ray_maxt_read_reg_2203_pp0_iter5_reg <= ray_maxt_read_reg_2203_pp0_iter4_reg;
        ray_maxt_read_reg_2203_pp0_iter6_reg <= ray_maxt_read_reg_2203_pp0_iter5_reg;
        ray_maxt_read_reg_2203_pp0_iter7_reg <= ray_maxt_read_reg_2203_pp0_iter6_reg;
        ray_maxt_read_reg_2203_pp0_iter8_reg <= ray_maxt_read_reg_2203_pp0_iter7_reg;
        ray_maxt_read_reg_2203_pp0_iter9_reg <= ray_maxt_read_reg_2203_pp0_iter8_reg;
        ray_mint_read_reg_2209 <= ray_mint;
        ray_mint_read_reg_2209_pp0_iter10_reg <= ray_mint_read_reg_2209_pp0_iter9_reg;
        ray_mint_read_reg_2209_pp0_iter11_reg <= ray_mint_read_reg_2209_pp0_iter10_reg;
        ray_mint_read_reg_2209_pp0_iter12_reg <= ray_mint_read_reg_2209_pp0_iter11_reg;
        ray_mint_read_reg_2209_pp0_iter1_reg <= ray_mint_read_reg_2209;
        ray_mint_read_reg_2209_pp0_iter2_reg <= ray_mint_read_reg_2209_pp0_iter1_reg;
        ray_mint_read_reg_2209_pp0_iter3_reg <= ray_mint_read_reg_2209_pp0_iter2_reg;
        ray_mint_read_reg_2209_pp0_iter4_reg <= ray_mint_read_reg_2209_pp0_iter3_reg;
        ray_mint_read_reg_2209_pp0_iter5_reg <= ray_mint_read_reg_2209_pp0_iter4_reg;
        ray_mint_read_reg_2209_pp0_iter6_reg <= ray_mint_read_reg_2209_pp0_iter5_reg;
        ray_mint_read_reg_2209_pp0_iter7_reg <= ray_mint_read_reg_2209_pp0_iter6_reg;
        ray_mint_read_reg_2209_pp0_iter8_reg <= ray_mint_read_reg_2209_pp0_iter7_reg;
        ray_mint_read_reg_2209_pp0_iter9_reg <= ray_mint_read_reg_2209_pp0_iter8_reg;
        select_ln43_1_reg_2599 <= select_ln43_1_fu_1126_p3;
        select_ln43_1_reg_2599_pp0_iter10_reg <= select_ln43_1_reg_2599;
        select_ln43_2_reg_2671 <= select_ln43_2_fu_1492_p3;
        select_ln43_2_reg_2671_pp0_iter12_reg <= select_ln43_2_reg_2671;
        select_ln43_3_reg_2679 <= select_ln43_3_fu_1499_p3;
        select_ln43_3_reg_2679_pp0_iter12_reg <= select_ln43_3_reg_2679;
        select_ln43_reg_2591 <= select_ln43_fu_1118_p3;
        select_ln43_reg_2591_pp0_iter10_reg <= select_ln43_reg_2591;
        select_ln49_1_reg_2545 <= select_ln49_1_fu_950_p3;
        select_ln49_2_reg_2552 <= select_ln49_2_fu_1038_p3;
        select_ln49_2_reg_2552_pp0_iter9_reg <= select_ln49_2_reg_2552;
        select_ln49_3_reg_2559 <= select_ln49_3_fu_1044_p3;
        select_ln49_3_reg_2559_pp0_iter9_reg <= select_ln49_3_reg_2559;
        select_ln49_4_reg_2627 <= select_ln49_4_fu_1412_p3;
        select_ln49_4_reg_2627_pp0_iter11_reg <= select_ln49_4_reg_2627;
        select_ln49_5_reg_2634 <= select_ln49_5_fu_1418_p3;
        select_ln49_5_reg_2634_pp0_iter11_reg <= select_ln49_5_reg_2634;
        select_ln49_reg_2538 <= select_ln49_fu_944_p3;
        select_ln52_1_reg_2693 <= select_ln52_1_fu_1608_p3;
        select_ln52_reg_2613 <= select_ln52_fu_1236_p3;
        select_ln53_1_reg_2700 <= select_ln53_1_fu_1696_p3;
        select_ln53_reg_2620 <= select_ln53_fu_1324_p3;
        tmp_5_1_reg_2470 <= grp_fu_196_p2;
        tmp_5_2_reg_2480 <= grp_fu_208_p2;
        tmp_5_reg_2460 <= grp_fu_184_p2;
        tmp_7_1_reg_2475 <= grp_fu_202_p2;
        tmp_7_2_reg_2485 <= grp_fu_214_p2;
        tmp_7_reg_2465 <= grp_fu_190_p2;
        xor_ln43_1_reg_2661 <= xor_ln43_1_fu_1482_p2;
        xor_ln43_1_reg_2661_pp0_iter12_reg <= xor_ln43_1_reg_2661;
        xor_ln43_1_reg_2661_pp0_iter13_reg <= xor_ln43_1_reg_2661_pp0_iter12_reg;
        xor_ln43_2_reg_2727 <= xor_ln43_2_fu_1760_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_fu_184_ce = 1'b1;
    end else begin
        grp_fu_184_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_fu_190_ce = 1'b1;
    end else begin
        grp_fu_190_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_fu_196_ce = 1'b1;
    end else begin
        grp_fu_196_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_fu_202_ce = 1'b1;
    end else begin
        grp_fu_202_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_fu_208_ce = 1'b1;
    end else begin
        grp_fu_208_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_fu_214_ce = 1'b1;
    end else begin
        grp_fu_214_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_fu_220_ce = 1'b1;
    end else begin
        grp_fu_220_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_fu_224_ce = 1'b1;
    end else begin
        grp_fu_224_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_fu_228_ce = 1'b1;
    end else begin
        grp_fu_228_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_fu_232_ce = 1'b1;
    end else begin
        grp_fu_232_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_fu_236_ce = 1'b1;
    end else begin
        grp_fu_236_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_fu_240_ce = 1'b1;
    end else begin
        grp_fu_240_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_fu_244_ce = 1'b1;
    end else begin
        grp_fu_244_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_fu_250_ce = 1'b1;
    end else begin
        grp_fu_250_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_fu_256_ce = 1'b1;
    end else begin
        grp_fu_256_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_fu_262_ce = 1'b1;
    end else begin
        grp_fu_262_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_fu_268_ce = 1'b1;
    end else begin
        grp_fu_268_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_fu_274_ce = 1'b1;
    end else begin
        grp_fu_274_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_fu_280_ce = 1'b1;
    end else begin
        grp_fu_280_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_fu_286_ce = 1'b1;
    end else begin
        grp_fu_286_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_fu_292_ce = 1'b1;
    end else begin
        grp_fu_292_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_fu_298_ce = 1'b1;
    end else begin
        grp_fu_298_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_fu_302_ce = 1'b1;
    end else begin
        grp_fu_302_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_fu_306_ce = 1'b1;
    end else begin
        grp_fu_306_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_fu_310_ce = 1'b1;
    end else begin
        grp_fu_310_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_fu_314_ce = 1'b1;
    end else begin
        grp_fu_314_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_fu_318_ce = 1'b1;
    end else begin
        grp_fu_318_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_fu_322_ce = 1'b1;
    end else begin
        grp_fu_322_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_fu_326_ce = 1'b1;
    end else begin
        grp_fu_326_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_fu_330_ce = 1'b1;
    end else begin
        grp_fu_330_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_fu_334_ce = 1'b1;
    end else begin
        grp_fu_334_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_fu_338_ce = 1'b1;
    end else begin
        grp_fu_338_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_fu_342_ce = 1'b1;
    end else begin
        grp_fu_342_ce = 1'b0;
    end
end

assign and_ln192_1_fu_1318_p2 = (grp_fu_314_p2 & and_ln192_fu_1312_p2);

assign and_ln192_2_fu_1684_p2 = (or_ln192_3_fu_1678_p2 & or_ln192_2_fu_1660_p2);

assign and_ln192_3_fu_1690_p2 = (grp_fu_330_p2 & and_ln192_2_fu_1684_p2);

assign and_ln192_fu_1312_p2 = (or_ln192_fu_1288_p2 & or_ln192_1_fu_1306_p2);

assign and_ln215_1_fu_1230_p2 = (grp_fu_310_p2 & and_ln215_fu_1224_p2);

assign and_ln215_2_fu_1596_p2 = (or_ln215_3_fu_1590_p2 & or_ln215_2_fu_1572_p2);

assign and_ln215_3_fu_1602_p2 = (grp_fu_326_p2 & and_ln215_2_fu_1596_p2);

assign and_ln215_fu_1224_p2 = (or_ln215_fu_1200_p2 & or_ln215_1_fu_1218_p2);

assign and_ln42_1_fu_774_p2 = (or_ln42_1_fu_770_p2 & grp_fu_262_p2);

assign and_ln42_2_fu_820_p2 = (or_ln42_2_fu_816_p2 & grp_fu_280_p2);

assign and_ln42_fu_728_p2 = (or_ln42_fu_724_p2 & grp_fu_244_p2);

assign and_ln43_10_fu_830_p2 = (or_ln43_9_fu_826_p2 & or_ln43_10_reg_2400);

assign and_ln43_11_fu_835_p2 = (grp_fu_286_p2 & and_ln43_10_fu_830_p2);

assign and_ln43_12_fu_845_p2 = (or_ln43_11_fu_841_p2 & or_ln43_10_reg_2400);

assign and_ln43_13_fu_850_p2 = (grp_fu_292_p2 & and_ln43_12_fu_845_p2);

assign and_ln43_14_fu_1765_p2 = (xor_ln43_2_fu_1760_p2 & and_ln42_2_reg_2445_pp0_iter12_reg);

assign and_ln43_15_fu_1984_p2 = (or_ln43_reg_2424_pp0_iter13_reg & and_ln42_reg_2416_pp0_iter13_reg);

assign and_ln43_16_fu_1999_p2 = (or_ln43_1_reg_2439_pp0_iter13_reg & and_ln42_1_reg_2430_pp0_iter13_reg);

assign and_ln43_17_fu_2014_p2 = (or_ln43_2_reg_2454_pp0_iter13_reg & and_ln42_2_reg_2445_pp0_iter13_reg);

assign and_ln43_18_fu_2080_p2 = (xor_ln43_1_reg_2661_pp0_iter13_reg & and_ln55_11_fu_2075_p2);

assign and_ln43_19_fu_2085_p2 = (and_ln43_18_fu_2080_p2 & and_ln42_1_reg_2430_pp0_iter13_reg);

assign and_ln43_1_fu_743_p2 = (grp_fu_250_p2 & and_ln43_fu_738_p2);

assign and_ln43_20_fu_2107_p2 = (xor_ln55_3_fu_2101_p2 & xor_ln43_2_reg_2727);

assign and_ln43_21_fu_2112_p2 = (and_ln43_20_fu_2107_p2 & and_ln42_2_reg_2445_pp0_iter13_reg);

assign and_ln43_2_fu_753_p2 = (or_ln43_5_fu_749_p2 & or_ln43_4_reg_2304);

assign and_ln43_3_fu_758_p2 = (grp_fu_256_p2 & and_ln43_2_fu_753_p2);

assign and_ln43_4_fu_1113_p2 = (xor_ln43_fu_1108_p2 & and_ln42_reg_2416_pp0_iter8_reg);

assign and_ln43_5_fu_784_p2 = (or_ln43_7_reg_2352 & or_ln43_6_fu_780_p2);

assign and_ln43_6_fu_789_p2 = (grp_fu_268_p2 & and_ln43_5_fu_784_p2);

assign and_ln43_7_fu_799_p2 = (or_ln43_8_fu_795_p2 & or_ln43_7_reg_2352);

assign and_ln43_8_fu_804_p2 = (grp_fu_274_p2 & and_ln43_7_fu_799_p2);

assign and_ln43_9_fu_1487_p2 = (xor_ln43_1_fu_1482_p2 & and_ln42_1_reg_2430_pp0_iter10_reg);

assign and_ln43_fu_738_p2 = (or_ln43_4_reg_2304 & or_ln43_3_fu_734_p2);

assign and_ln49_1_fu_938_p2 = (grp_fu_298_p2 & and_ln49_fu_932_p2);

assign and_ln49_2_fu_1026_p2 = (or_ln49_3_fu_1020_p2 & or_ln49_2_fu_1002_p2);

assign and_ln49_3_fu_1032_p2 = (grp_fu_302_p2 & and_ln49_2_fu_1026_p2);

assign and_ln49_4_fu_1400_p2 = (or_ln49_5_fu_1394_p2 & or_ln49_4_fu_1376_p2);

assign and_ln49_5_fu_1406_p2 = (grp_fu_318_p2 & and_ln49_4_fu_1400_p2);

assign and_ln49_fu_932_p2 = (or_ln49_fu_908_p2 & or_ln49_1_fu_926_p2);

assign and_ln55_10_fu_2065_p2 = (xor_ln42_1_fu_2003_p2 & and_ln55_3_reg_2687_pp0_iter13_reg);

assign and_ln55_11_fu_2075_p2 = (xor_ln42_fu_1988_p2 & and_ln55_1_reg_2607_pp0_iter13_reg);

assign and_ln55_12_fu_2144_p2 = (or_ln55_17_fu_2139_p2 & and_ln43_4_reg_2586_pp0_iter13_reg);

assign and_ln55_13_fu_2149_p2 = (or_ln55_16_fu_2134_p2 & and_ln55_12_fu_2144_p2);

assign and_ln55_14_fu_2155_p2 = (or_ln55_16_fu_2134_p2 & and_ln43_19_fu_2085_p2);

assign and_ln55_1_fu_1148_p2 = (grp_fu_306_p2 & and_ln55_fu_1142_p2);

assign and_ln55_2_fu_1514_p2 = (or_ln55_3_fu_1510_p2 & or_ln55_2_fu_1506_p2);

assign and_ln55_3_fu_1520_p2 = (grp_fu_322_p2 & and_ln55_2_fu_1514_p2);

assign and_ln55_4_fu_1920_p2 = (or_ln55_5_fu_1916_p2 & or_ln55_4_fu_1912_p2);

assign and_ln55_5_fu_1926_p2 = (grp_fu_334_p2 & and_ln55_4_fu_1920_p2);

assign and_ln55_6_fu_1993_p2 = (xor_ln55_fu_1902_p2 & xor_ln42_fu_1988_p2);

assign and_ln55_7_fu_2008_p2 = (xor_ln55_1_fu_1907_p2 & xor_ln42_1_fu_2003_p2);

assign and_ln55_8_fu_2023_p2 = (xor_ln55_2_fu_1932_p2 & xor_ln42_2_fu_2018_p2);

assign and_ln55_9_fu_2059_p2 = (xor_ln42_2_fu_2018_p2 & and_ln55_5_fu_1926_p2);

assign and_ln55_fu_1142_p2 = (or_ln55_fu_1134_p2 & or_ln55_1_fu_1138_p2);

assign and_ln60_1_fu_1952_p2 = (grp_fu_338_p2 & and_ln60_fu_1946_p2);

assign and_ln60_2_fu_1972_p2 = (or_ln60_3_fu_1968_p2 & or_ln60_2_fu_1964_p2);

assign and_ln60_3_fu_1978_p2 = (grp_fu_342_p2 & and_ln60_2_fu_1972_p2);

assign and_ln60_fu_1946_p2 = (or_ln60_fu_1938_p2 & or_ln60_1_fu_1942_p2);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_return = (tmp140_fu_2191_p2 & and_ln60_3_fu_1978_p2);

assign bitcast_ln192_1_fu_1259_p1 = select_ln49_2_reg_2552_pp0_iter9_reg;

assign bitcast_ln192_2_fu_1614_p1 = select_ln43_3_reg_2679;

assign bitcast_ln192_3_fu_1631_p1 = select_ln49_4_reg_2627_pp0_iter11_reg;

assign bitcast_ln192_fu_1242_p1 = select_ln43_1_reg_2599;

assign bitcast_ln215_1_fu_1171_p1 = select_ln43_reg_2591;

assign bitcast_ln215_2_fu_1526_p1 = select_ln49_5_reg_2634_pp0_iter11_reg;

assign bitcast_ln215_3_fu_1543_p1 = select_ln43_2_reg_2671;

assign bitcast_ln215_fu_1154_p1 = select_ln49_3_reg_2559_pp0_iter9_reg;

assign bitcast_ln42_1_fu_472_p1 = ray_d_1;

assign bitcast_ln42_2_fu_598_p1 = ray_d_2;

assign bitcast_ln42_fu_346_p1 = ray_d_0;

assign bitcast_ln43_1_fu_394_p1 = ray_o_0;

assign bitcast_ln43_2_fu_442_p1 = max_0;

assign bitcast_ln43_3_fu_502_p1 = min_1;

assign bitcast_ln43_4_fu_520_p1 = ray_o_1;

assign bitcast_ln43_5_fu_568_p1 = max_1;

assign bitcast_ln43_6_fu_628_p1 = min_2;

assign bitcast_ln43_7_fu_646_p1 = ray_o_2;

assign bitcast_ln43_8_fu_694_p1 = max_2;

assign bitcast_ln43_fu_376_p1 = min_0;

assign bitcast_ln49_1_fu_879_p1 = p_b_read_assign_reg_2498_pp0_iter7_reg;

assign bitcast_ln49_2_fu_956_p1 = p_tmp_1_reg_2506_pp0_iter7_reg;

assign bitcast_ln49_3_fu_973_p1 = p_b_read_assign_1_reg_2514_pp0_iter7_reg;

assign bitcast_ln49_4_fu_1330_p1 = p_tmp_2_reg_2522_pp0_iter9_reg;

assign bitcast_ln49_5_fu_1347_p1 = p_b_read_assign_2_reg_2530_pp0_iter9_reg;

assign bitcast_ln49_fu_862_p1 = p_tmp_reg_2490_pp0_iter7_reg;

assign bitcast_ln55_1_fu_1067_p1 = select_ln49_reg_2538;

assign bitcast_ln55_2_fu_1424_p1 = select_ln52_reg_2613;

assign bitcast_ln55_3_fu_1441_p1 = select_ln53_reg_2620;

assign bitcast_ln55_4_fu_1702_p1 = select_ln52_1_reg_2693;

assign bitcast_ln55_5_fu_1719_p1 = select_ln53_1_reg_2700;

assign bitcast_ln55_fu_1050_p1 = select_ln49_1_reg_2545;

assign bitcast_ln60_1_fu_1802_p1 = ray_mint_read_reg_2209_pp0_iter12_reg;

assign bitcast_ln60_2_fu_1843_p1 = select_ln43_4_fu_1770_p3;

assign bitcast_ln60_3_fu_1861_p1 = ray_maxt_read_reg_2203_pp0_iter12_reg;

assign bitcast_ln60_fu_1784_p1 = select_ln43_5_fu_1777_p3;

assign grp_fu_310_p1 = ((and_ln43_4_fu_1113_p2[0:0] === 1'b1) ? 32'd4286578688 : select_ln49_1_reg_2545);

assign grp_fu_314_p0 = ((and_ln43_4_fu_1113_p2[0:0] === 1'b1) ? 32'd2139095040 : select_ln49_reg_2538);

assign grp_fu_326_p1 = ((and_ln43_9_fu_1487_p2[0:0] === 1'b1) ? select_ln43_reg_2591_pp0_iter10_reg : select_ln52_reg_2613);

assign grp_fu_330_p0 = ((and_ln43_9_fu_1487_p2[0:0] === 1'b1) ? select_ln43_1_reg_2599_pp0_iter10_reg : select_ln53_reg_2620);

assign icmp_ln192_1_fu_1282_p2 = ((trunc_ln192_fu_1255_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln192_2_fu_1294_p2 = ((tmp_28_fu_1262_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln192_3_fu_1300_p2 = ((trunc_ln192_1_fu_1272_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln192_4_fu_1648_p2 = ((tmp_46_fu_1617_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln192_5_fu_1654_p2 = ((trunc_ln192_2_fu_1627_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln192_6_fu_1666_p2 = ((tmp_47_fu_1634_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln192_7_fu_1672_p2 = ((trunc_ln192_3_fu_1644_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln192_fu_1276_p2 = ((tmp_27_fu_1245_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln215_1_fu_1194_p2 = ((trunc_ln215_fu_1167_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln215_2_fu_1206_p2 = ((tmp_25_fu_1174_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln215_3_fu_1212_p2 = ((trunc_ln215_1_fu_1184_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln215_4_fu_1560_p2 = ((tmp_43_fu_1529_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln215_5_fu_1566_p2 = ((trunc_ln215_2_fu_1539_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln215_6_fu_1578_p2 = ((tmp_44_fu_1546_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln215_7_fu_1584_p2 = ((trunc_ln215_3_fu_1556_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln215_fu_1188_p2 = ((tmp_24_fu_1157_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln42_1_fu_370_p2 = ((trunc_ln42_fu_360_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln42_2_fu_490_p2 = ((tmp_14_fu_476_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln42_3_fu_496_p2 = ((trunc_ln42_1_fu_486_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln42_4_fu_616_p2 = ((tmp_33_fu_602_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln42_5_fu_622_p2 = ((trunc_ln42_2_fu_612_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln42_fu_364_p2 = ((tmp_fu_350_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln43_10_fu_586_p2 = ((tmp_19_fu_572_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln43_11_fu_592_p2 = ((trunc_ln43_5_fu_582_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln43_12_fu_664_p2 = ((tmp_35_fu_632_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln43_13_fu_670_p2 = ((trunc_ln43_6_fu_642_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln43_14_fu_676_p2 = ((tmp_36_fu_650_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln43_15_fu_682_p2 = ((trunc_ln43_7_fu_660_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln43_16_fu_712_p2 = ((tmp_38_fu_698_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln43_17_fu_718_p2 = ((trunc_ln43_8_fu_708_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln43_1_fu_418_p2 = ((trunc_ln43_fu_390_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln43_2_fu_424_p2 = ((tmp_3_fu_398_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln43_3_fu_430_p2 = ((trunc_ln43_1_fu_408_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln43_4_fu_460_p2 = ((tmp_6_fu_446_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln43_5_fu_466_p2 = ((trunc_ln43_2_fu_456_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln43_6_fu_538_p2 = ((tmp_16_fu_506_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln43_7_fu_544_p2 = ((trunc_ln43_3_fu_516_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln43_8_fu_550_p2 = ((tmp_17_fu_524_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln43_9_fu_556_p2 = ((trunc_ln43_4_fu_534_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln43_fu_412_p2 = ((tmp_2_fu_380_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln49_10_fu_1382_p2 = ((tmp_41_fu_1350_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln49_11_fu_1388_p2 = ((trunc_ln49_5_fu_1360_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln49_1_fu_902_p2 = ((trunc_ln49_fu_875_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln49_2_fu_914_p2 = ((tmp_8_fu_882_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln49_3_fu_920_p2 = ((trunc_ln49_1_fu_892_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln49_4_fu_990_p2 = ((tmp_21_fu_959_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln49_5_fu_996_p2 = ((trunc_ln49_2_fu_969_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln49_6_fu_1008_p2 = ((tmp_22_fu_976_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln49_7_fu_1014_p2 = ((trunc_ln49_3_fu_986_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln49_8_fu_1364_p2 = ((tmp_40_fu_1333_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln49_9_fu_1370_p2 = ((trunc_ln49_4_fu_1343_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln49_fu_896_p2 = ((tmp_s_fu_865_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln55_10_fu_1748_p2 = ((tmp_50_fu_1722_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln55_11_fu_1754_p2 = ((trunc_ln55_5_fu_1732_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln55_1_fu_1090_p2 = ((trunc_ln55_fu_1063_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln55_2_fu_1096_p2 = ((tmp_12_fu_1070_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln55_3_fu_1102_p2 = ((trunc_ln55_1_fu_1080_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln55_4_fu_1458_p2 = ((tmp_30_fu_1427_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln55_5_fu_1464_p2 = ((trunc_ln55_2_fu_1437_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln55_6_fu_1470_p2 = ((tmp_31_fu_1444_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln55_7_fu_1476_p2 = ((trunc_ln55_3_fu_1454_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln55_8_fu_1736_p2 = ((tmp_49_fu_1705_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln55_9_fu_1742_p2 = ((trunc_ln55_4_fu_1715_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln55_fu_1084_p2 = ((tmp_11_fu_1053_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln60_1_fu_1825_p2 = ((trunc_ln60_fu_1798_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln60_2_fu_1831_p2 = ((tmp_53_fu_1805_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln60_3_fu_1837_p2 = ((trunc_ln60_1_fu_1815_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln60_4_fu_1878_p2 = ((tmp_55_fu_1847_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln60_5_fu_1884_p2 = ((trunc_ln60_2_fu_1857_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln60_6_fu_1890_p2 = ((tmp_56_fu_1864_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln60_7_fu_1896_p2 = ((trunc_ln60_3_fu_1874_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln60_fu_1819_p2 = ((tmp_52_fu_1788_p4 != 8'd255) ? 1'b1 : 1'b0);

assign or_ln192_1_fu_1306_p2 = (icmp_ln192_3_fu_1300_p2 | icmp_ln192_2_fu_1294_p2);

assign or_ln192_2_fu_1660_p2 = (icmp_ln192_5_fu_1654_p2 | icmp_ln192_4_fu_1648_p2);

assign or_ln192_3_fu_1678_p2 = (icmp_ln192_7_fu_1672_p2 | icmp_ln192_6_fu_1666_p2);

assign or_ln192_fu_1288_p2 = (icmp_ln192_fu_1276_p2 | icmp_ln192_1_fu_1282_p2);

assign or_ln215_1_fu_1218_p2 = (icmp_ln215_3_fu_1212_p2 | icmp_ln215_2_fu_1206_p2);

assign or_ln215_2_fu_1572_p2 = (icmp_ln215_5_fu_1566_p2 | icmp_ln215_4_fu_1560_p2);

assign or_ln215_3_fu_1590_p2 = (icmp_ln215_7_fu_1584_p2 | icmp_ln215_6_fu_1578_p2);

assign or_ln215_fu_1200_p2 = (icmp_ln215_fu_1188_p2 | icmp_ln215_1_fu_1194_p2);

assign or_ln42_1_fu_770_p2 = (icmp_ln42_3_reg_2337 | icmp_ln42_2_reg_2332);

assign or_ln42_2_fu_816_p2 = (icmp_ln42_5_reg_2385 | icmp_ln42_4_reg_2380);

assign or_ln42_fu_724_p2 = (icmp_ln42_reg_2284 | icmp_ln42_1_reg_2289);

assign or_ln43_10_fu_688_p2 = (icmp_ln43_15_fu_682_p2 | icmp_ln43_14_fu_676_p2);

assign or_ln43_11_fu_841_p2 = (icmp_ln43_17_reg_2411 | icmp_ln43_16_reg_2406);

assign or_ln43_1_fu_810_p2 = (and_ln43_8_fu_804_p2 | and_ln43_6_fu_789_p2);

assign or_ln43_2_fu_856_p2 = (and_ln43_13_fu_850_p2 | and_ln43_11_fu_835_p2);

assign or_ln43_3_fu_734_p2 = (icmp_ln43_reg_2294 | icmp_ln43_1_reg_2299);

assign or_ln43_4_fu_436_p2 = (icmp_ln43_3_fu_430_p2 | icmp_ln43_2_fu_424_p2);

assign or_ln43_5_fu_749_p2 = (icmp_ln43_5_reg_2315 | icmp_ln43_4_reg_2310);

assign or_ln43_6_fu_780_p2 = (icmp_ln43_7_reg_2347 | icmp_ln43_6_reg_2342);

assign or_ln43_7_fu_562_p2 = (icmp_ln43_9_fu_556_p2 | icmp_ln43_8_fu_550_p2);

assign or_ln43_8_fu_795_p2 = (icmp_ln43_11_reg_2363 | icmp_ln43_10_reg_2358);

assign or_ln43_9_fu_826_p2 = (icmp_ln43_13_reg_2395 | icmp_ln43_12_reg_2390);

assign or_ln43_fu_764_p2 = (and_ln43_3_fu_758_p2 | and_ln43_1_fu_743_p2);

assign or_ln49_1_fu_926_p2 = (icmp_ln49_3_fu_920_p2 | icmp_ln49_2_fu_914_p2);

assign or_ln49_2_fu_1002_p2 = (icmp_ln49_5_fu_996_p2 | icmp_ln49_4_fu_990_p2);

assign or_ln49_3_fu_1020_p2 = (icmp_ln49_7_fu_1014_p2 | icmp_ln49_6_fu_1008_p2);

assign or_ln49_4_fu_1376_p2 = (icmp_ln49_9_fu_1370_p2 | icmp_ln49_8_fu_1364_p2);

assign or_ln49_5_fu_1394_p2 = (icmp_ln49_11_fu_1388_p2 | icmp_ln49_10_fu_1382_p2);

assign or_ln49_fu_908_p2 = (icmp_ln49_fu_896_p2 | icmp_ln49_1_fu_902_p2);

assign or_ln55_10_fu_2053_p2 = (or_ln55_9_fu_2047_p2 | or_ln55_7_fu_2035_p2);

assign or_ln55_11_fu_2070_p2 = (xor_ln55_fu_1902_p2 | and_ln42_reg_2416_pp0_iter13_reg);

assign or_ln55_12_fu_2090_p2 = (xor_ln55_1_fu_1907_p2 | and_ln42_1_reg_2430_pp0_iter13_reg);

assign or_ln55_13_fu_2095_p2 = (or_ln55_12_fu_2090_p2 | or_ln55_11_fu_2070_p2);

assign or_ln55_14_fu_2117_p2 = (xor_ln55_2_fu_1932_p2 | and_ln42_2_reg_2445_pp0_iter13_reg);

assign or_ln55_15_fu_2122_p2 = (or_ln55_14_fu_2117_p2 | or_ln55_13_fu_2095_p2);

assign or_ln55_16_fu_2134_p2 = (and_ln55_9_fu_2059_p2 | and_ln43_14_reg_2732);

assign or_ln55_17_fu_2139_p2 = (and_ln55_10_fu_2065_p2 | and_ln43_9_reg_2666_pp0_iter13_reg);

assign or_ln55_18_fu_2161_p2 = (xor_ln55_4_fu_2128_p2 | and_ln43_21_fu_2112_p2);

assign or_ln55_19_fu_2167_p2 = (or_ln55_18_fu_2161_p2 | and_ln55_14_fu_2155_p2);

assign or_ln55_1_fu_1138_p2 = (icmp_ln55_3_reg_2581 | icmp_ln55_2_reg_2576);

assign or_ln55_20_fu_2173_p2 = (or_ln55_19_fu_2167_p2 | and_ln55_13_fu_2149_p2);

assign or_ln55_2_fu_1506_p2 = (icmp_ln55_5_reg_2646 | icmp_ln55_4_reg_2641);

assign or_ln55_3_fu_1510_p2 = (icmp_ln55_7_reg_2656 | icmp_ln55_6_reg_2651);

assign or_ln55_4_fu_1912_p2 = (icmp_ln55_9_reg_2712 | icmp_ln55_8_reg_2707);

assign or_ln55_5_fu_1916_p2 = (icmp_ln55_11_reg_2722 | icmp_ln55_10_reg_2717);

assign or_ln55_6_fu_2029_p2 = (and_ln55_6_fu_1993_p2 | and_ln43_16_fu_1999_p2);

assign or_ln55_7_fu_2035_p2 = (or_ln55_6_fu_2029_p2 | and_ln43_15_fu_1984_p2);

assign or_ln55_8_fu_2041_p2 = (and_ln55_8_fu_2023_p2 | and_ln43_17_fu_2014_p2);

assign or_ln55_9_fu_2047_p2 = (or_ln55_8_fu_2041_p2 | and_ln55_7_fu_2008_p2);

assign or_ln55_fu_1134_p2 = (icmp_ln55_reg_2566 | icmp_ln55_1_reg_2571);

assign or_ln60_1_fu_1942_p2 = (icmp_ln60_3_reg_2762 | icmp_ln60_2_reg_2757);

assign or_ln60_2_fu_1964_p2 = (icmp_ln60_5_reg_2772 | icmp_ln60_4_reg_2767);

assign or_ln60_3_fu_1968_p2 = (icmp_ln60_7_reg_2782 | icmp_ln60_6_reg_2777);

assign or_ln60_fu_1938_p2 = (icmp_ln60_reg_2747 | icmp_ln60_1_reg_2752);

assign sel_tmp116_fu_2179_p2 = (xor_ln60_fu_1958_p2 & or_ln55_20_fu_2173_p2);

assign select_ln43_1_fu_1126_p3 = ((and_ln43_4_fu_1113_p2[0:0] === 1'b1) ? 32'd2139095040 : select_ln49_reg_2538);

assign select_ln43_2_fu_1492_p3 = ((and_ln43_9_fu_1487_p2[0:0] === 1'b1) ? select_ln43_reg_2591_pp0_iter10_reg : select_ln52_reg_2613);

assign select_ln43_3_fu_1499_p3 = ((and_ln43_9_fu_1487_p2[0:0] === 1'b1) ? select_ln43_1_reg_2599_pp0_iter10_reg : select_ln53_reg_2620);

assign select_ln43_4_fu_1770_p3 = ((and_ln43_14_fu_1765_p2[0:0] === 1'b1) ? select_ln43_2_reg_2671_pp0_iter12_reg : select_ln52_1_reg_2693);

assign select_ln43_5_fu_1777_p3 = ((and_ln43_14_fu_1765_p2[0:0] === 1'b1) ? select_ln43_3_reg_2679_pp0_iter12_reg : select_ln53_1_reg_2700);

assign select_ln43_fu_1118_p3 = ((and_ln43_4_fu_1113_p2[0:0] === 1'b1) ? 32'd4286578688 : select_ln49_1_reg_2545);

assign select_ln49_1_fu_950_p3 = ((and_ln49_1_fu_938_p2[0:0] === 1'b1) ? p_b_read_assign_reg_2498_pp0_iter7_reg : p_tmp_reg_2490_pp0_iter7_reg);

assign select_ln49_2_fu_1038_p3 = ((and_ln49_3_fu_1032_p2[0:0] === 1'b1) ? p_tmp_1_reg_2506_pp0_iter7_reg : p_b_read_assign_1_reg_2514_pp0_iter7_reg);

assign select_ln49_3_fu_1044_p3 = ((and_ln49_3_fu_1032_p2[0:0] === 1'b1) ? p_b_read_assign_1_reg_2514_pp0_iter7_reg : p_tmp_1_reg_2506_pp0_iter7_reg);

assign select_ln49_4_fu_1412_p3 = ((and_ln49_5_fu_1406_p2[0:0] === 1'b1) ? p_tmp_2_reg_2522_pp0_iter9_reg : p_b_read_assign_2_reg_2530_pp0_iter9_reg);

assign select_ln49_5_fu_1418_p3 = ((and_ln49_5_fu_1406_p2[0:0] === 1'b1) ? p_b_read_assign_2_reg_2530_pp0_iter9_reg : p_tmp_2_reg_2522_pp0_iter9_reg);

assign select_ln49_fu_944_p3 = ((and_ln49_1_fu_938_p2[0:0] === 1'b1) ? p_tmp_reg_2490_pp0_iter7_reg : p_b_read_assign_reg_2498_pp0_iter7_reg);

assign select_ln52_1_fu_1608_p3 = ((and_ln215_3_fu_1602_p2[0:0] === 1'b1) ? select_ln43_2_reg_2671 : select_ln49_5_reg_2634_pp0_iter11_reg);

assign select_ln52_fu_1236_p3 = ((and_ln215_1_fu_1230_p2[0:0] === 1'b1) ? select_ln43_reg_2591 : select_ln49_3_reg_2559_pp0_iter9_reg);

assign select_ln53_1_fu_1696_p3 = ((and_ln192_3_fu_1690_p2[0:0] === 1'b1) ? select_ln43_3_reg_2679 : select_ln49_4_reg_2627_pp0_iter11_reg);

assign select_ln53_fu_1324_p3 = ((and_ln192_1_fu_1318_p2[0:0] === 1'b1) ? select_ln43_1_reg_2599 : select_ln49_2_reg_2552_pp0_iter9_reg);

assign tmp140_demorgan_fu_2185_p2 = (sel_tmp116_fu_2179_p2 | or_ln55_10_fu_2053_p2);

assign tmp140_fu_2191_p2 = (tmp140_demorgan_fu_2185_p2 ^ 1'd1);

assign tmp_11_fu_1053_p4 = {{bitcast_ln55_fu_1050_p1[30:23]}};

assign tmp_12_fu_1070_p4 = {{bitcast_ln55_1_fu_1067_p1[30:23]}};

assign tmp_14_fu_476_p4 = {{bitcast_ln42_1_fu_472_p1[30:23]}};

assign tmp_16_fu_506_p4 = {{bitcast_ln43_3_fu_502_p1[30:23]}};

assign tmp_17_fu_524_p4 = {{bitcast_ln43_4_fu_520_p1[30:23]}};

assign tmp_19_fu_572_p4 = {{bitcast_ln43_5_fu_568_p1[30:23]}};

assign tmp_21_fu_959_p4 = {{bitcast_ln49_2_fu_956_p1[30:23]}};

assign tmp_22_fu_976_p4 = {{bitcast_ln49_3_fu_973_p1[30:23]}};

assign tmp_24_fu_1157_p4 = {{bitcast_ln215_fu_1154_p1[30:23]}};

assign tmp_25_fu_1174_p4 = {{bitcast_ln215_1_fu_1171_p1[30:23]}};

assign tmp_27_fu_1245_p4 = {{bitcast_ln192_fu_1242_p1[30:23]}};

assign tmp_28_fu_1262_p4 = {{bitcast_ln192_1_fu_1259_p1[30:23]}};

assign tmp_2_fu_380_p4 = {{bitcast_ln43_fu_376_p1[30:23]}};

assign tmp_30_fu_1427_p4 = {{bitcast_ln55_2_fu_1424_p1[30:23]}};

assign tmp_31_fu_1444_p4 = {{bitcast_ln55_3_fu_1441_p1[30:23]}};

assign tmp_33_fu_602_p4 = {{bitcast_ln42_2_fu_598_p1[30:23]}};

assign tmp_35_fu_632_p4 = {{bitcast_ln43_6_fu_628_p1[30:23]}};

assign tmp_36_fu_650_p4 = {{bitcast_ln43_7_fu_646_p1[30:23]}};

assign tmp_38_fu_698_p4 = {{bitcast_ln43_8_fu_694_p1[30:23]}};

assign tmp_3_fu_398_p4 = {{bitcast_ln43_1_fu_394_p1[30:23]}};

assign tmp_40_fu_1333_p4 = {{bitcast_ln49_4_fu_1330_p1[30:23]}};

assign tmp_41_fu_1350_p4 = {{bitcast_ln49_5_fu_1347_p1[30:23]}};

assign tmp_43_fu_1529_p4 = {{bitcast_ln215_2_fu_1526_p1[30:23]}};

assign tmp_44_fu_1546_p4 = {{bitcast_ln215_3_fu_1543_p1[30:23]}};

assign tmp_46_fu_1617_p4 = {{bitcast_ln192_2_fu_1614_p1[30:23]}};

assign tmp_47_fu_1634_p4 = {{bitcast_ln192_3_fu_1631_p1[30:23]}};

assign tmp_49_fu_1705_p4 = {{bitcast_ln55_4_fu_1702_p1[30:23]}};

assign tmp_50_fu_1722_p4 = {{bitcast_ln55_5_fu_1719_p1[30:23]}};

assign tmp_52_fu_1788_p4 = {{bitcast_ln60_fu_1784_p1[30:23]}};

assign tmp_53_fu_1805_p4 = {{bitcast_ln60_1_fu_1802_p1[30:23]}};

assign tmp_55_fu_1847_p4 = {{bitcast_ln60_2_fu_1843_p1[30:23]}};

assign tmp_56_fu_1864_p4 = {{bitcast_ln60_3_fu_1861_p1[30:23]}};

assign tmp_6_fu_446_p4 = {{bitcast_ln43_2_fu_442_p1[30:23]}};

assign tmp_8_fu_882_p4 = {{bitcast_ln49_1_fu_879_p1[30:23]}};

assign tmp_fu_350_p4 = {{bitcast_ln42_fu_346_p1[30:23]}};

assign tmp_s_fu_865_p4 = {{bitcast_ln49_fu_862_p1[30:23]}};

assign trunc_ln192_1_fu_1272_p1 = bitcast_ln192_1_fu_1259_p1[22:0];

assign trunc_ln192_2_fu_1627_p1 = bitcast_ln192_2_fu_1614_p1[22:0];

assign trunc_ln192_3_fu_1644_p1 = bitcast_ln192_3_fu_1631_p1[22:0];

assign trunc_ln192_fu_1255_p1 = bitcast_ln192_fu_1242_p1[22:0];

assign trunc_ln215_1_fu_1184_p1 = bitcast_ln215_1_fu_1171_p1[22:0];

assign trunc_ln215_2_fu_1539_p1 = bitcast_ln215_2_fu_1526_p1[22:0];

assign trunc_ln215_3_fu_1556_p1 = bitcast_ln215_3_fu_1543_p1[22:0];

assign trunc_ln215_fu_1167_p1 = bitcast_ln215_fu_1154_p1[22:0];

assign trunc_ln42_1_fu_486_p1 = bitcast_ln42_1_fu_472_p1[22:0];

assign trunc_ln42_2_fu_612_p1 = bitcast_ln42_2_fu_598_p1[22:0];

assign trunc_ln42_fu_360_p1 = bitcast_ln42_fu_346_p1[22:0];

assign trunc_ln43_1_fu_408_p1 = bitcast_ln43_1_fu_394_p1[22:0];

assign trunc_ln43_2_fu_456_p1 = bitcast_ln43_2_fu_442_p1[22:0];

assign trunc_ln43_3_fu_516_p1 = bitcast_ln43_3_fu_502_p1[22:0];

assign trunc_ln43_4_fu_534_p1 = bitcast_ln43_4_fu_520_p1[22:0];

assign trunc_ln43_5_fu_582_p1 = bitcast_ln43_5_fu_568_p1[22:0];

assign trunc_ln43_6_fu_642_p1 = bitcast_ln43_6_fu_628_p1[22:0];

assign trunc_ln43_7_fu_660_p1 = bitcast_ln43_7_fu_646_p1[22:0];

assign trunc_ln43_8_fu_708_p1 = bitcast_ln43_8_fu_694_p1[22:0];

assign trunc_ln43_fu_390_p1 = bitcast_ln43_fu_376_p1[22:0];

assign trunc_ln49_1_fu_892_p1 = bitcast_ln49_1_fu_879_p1[22:0];

assign trunc_ln49_2_fu_969_p1 = bitcast_ln49_2_fu_956_p1[22:0];

assign trunc_ln49_3_fu_986_p1 = bitcast_ln49_3_fu_973_p1[22:0];

assign trunc_ln49_4_fu_1343_p1 = bitcast_ln49_4_fu_1330_p1[22:0];

assign trunc_ln49_5_fu_1360_p1 = bitcast_ln49_5_fu_1347_p1[22:0];

assign trunc_ln49_fu_875_p1 = bitcast_ln49_fu_862_p1[22:0];

assign trunc_ln55_1_fu_1080_p1 = bitcast_ln55_1_fu_1067_p1[22:0];

assign trunc_ln55_2_fu_1437_p1 = bitcast_ln55_2_fu_1424_p1[22:0];

assign trunc_ln55_3_fu_1454_p1 = bitcast_ln55_3_fu_1441_p1[22:0];

assign trunc_ln55_4_fu_1715_p1 = bitcast_ln55_4_fu_1702_p1[22:0];

assign trunc_ln55_5_fu_1732_p1 = bitcast_ln55_5_fu_1719_p1[22:0];

assign trunc_ln55_fu_1063_p1 = bitcast_ln55_fu_1050_p1[22:0];

assign trunc_ln60_1_fu_1815_p1 = bitcast_ln60_1_fu_1802_p1[22:0];

assign trunc_ln60_2_fu_1857_p1 = bitcast_ln60_2_fu_1843_p1[22:0];

assign trunc_ln60_3_fu_1874_p1 = bitcast_ln60_3_fu_1861_p1[22:0];

assign trunc_ln60_fu_1798_p1 = bitcast_ln60_fu_1784_p1[22:0];

assign xor_ln42_1_fu_2003_p2 = (1'd1 ^ and_ln42_1_reg_2430_pp0_iter13_reg);

assign xor_ln42_2_fu_2018_p2 = (1'd1 ^ and_ln42_2_reg_2445_pp0_iter13_reg);

assign xor_ln42_fu_1988_p2 = (1'd1 ^ and_ln42_reg_2416_pp0_iter13_reg);

assign xor_ln43_1_fu_1482_p2 = (or_ln43_1_reg_2439_pp0_iter10_reg ^ 1'd1);

assign xor_ln43_2_fu_1760_p2 = (or_ln43_2_reg_2454_pp0_iter12_reg ^ 1'd1);

assign xor_ln43_fu_1108_p2 = (or_ln43_reg_2424_pp0_iter8_reg ^ 1'd1);

assign xor_ln55_1_fu_1907_p2 = (1'd1 ^ and_ln55_3_reg_2687_pp0_iter13_reg);

assign xor_ln55_2_fu_1932_p2 = (1'd1 ^ and_ln55_5_fu_1926_p2);

assign xor_ln55_3_fu_2101_p2 = (or_ln55_13_fu_2095_p2 ^ 1'd1);

assign xor_ln55_4_fu_2128_p2 = (or_ln55_15_fu_2122_p2 ^ 1'd1);

assign xor_ln55_fu_1902_p2 = (1'd1 ^ and_ln55_1_reg_2607_pp0_iter13_reg);

assign xor_ln60_fu_1958_p2 = (1'd1 ^ and_ln60_1_fu_1952_p2);

endmodule //Bbox_RayIntersect
